// This code was automatically generated by FPGA Register Builder
// Timestamp: 2020-08-20 12:34:28.472
// User: madorsky
// FPGA MGT+Register builder homepage: github.com/madorskya/mgt_builder

`ifndef RBLD_INTERFACE_SV
`define RBLD_INTERFACE_SV

interface rbld_iface;

	logic gth_rst;
	logic inject_test_data;
	logic spy_mem_rst;
	logic gth_rx_buf_rst;
	logic latency_test_en;
	logic daq_rst;
	logic force_oos;
	logic mpc_links_hr_en;
	logic [9:0] csc_link_id [4:0] [9:2];
	logic [9:0] csc_link_id_n [8:0];
	logic [7:0] cppf_link_id [7:1];
	logic [7:1] cppf_crc_match;
	logic [9:2] csc_fiber_en [4:0];
	logic [9:1] csc_fiber_en_n;
	logic [6:0] cppf_fiber_en;
	logic [6:0] ge11_fiber_en;
	logic [4:0] csc_auto_delay [4:0] [9:2];
	logic [4:0] csc_auto_delay_id1 [4:0] [7:0];
	logic [4:0] csc_auto_delay_n [9:1];
	logic [4:0] csc_manual_delay [4:0] [9:2];
	logic [4:0] csc_manual_delay_id1 [4:0] [7:0];
	logic [4:0] csc_manual_delay_n [9:1];
	logic endcap;
	logic [2:0] sector;
	logic [8:0] spy_data_delay;
	logic spy_write_at_l1a;
	logic spy_write_at_stub;
	logic spy_write_at_rank;
	logic af_en;
	logic tst_data_inj_en;
	logic tst_data_inj_on_mpc_inj_cmd;
	logic [2:0] gth_prbs_mode;
	logic [8:0] af_ttc_bc0_delay;
	logic [11:0] gmt_link_comma_delay;
	logic [5:0] cppf_ttc_bc0_delay;
	logic [9:2] csc_alg_out_range [4:0];
	logic [7:0] csc_alg_out_range_id1 [4:0];
	logic [9:1] csc_alg_out_range_n;
	logic [9:2] csc_bc0_period_err [4:0];
	logic [7:0] csc_bc0_period_err_id1 [4:0];
	logic [9:1] csc_bc0_period_err_n;
	logic [7:0] csc_crc_err [4:0];
	logic [8:0] csc_crc_err_n;
	logic [7:0] csc_tst_pat_err [4:0];
	logic [8:0] csc_tst_pat_err_n;
	logic [9:0] spy_current_addr;
	logic [31:0] abs_time_cnt;
	logic [5:0] core_fpga_fw_sec;
	logic [5:0] core_fpga_fw_min;
	logic [4:0] core_fpga_fw_hour;
	logic [5:0] core_fpga_fw_year;
	logic [3:0] core_fpga_fw_month;
	logic [4:0] core_fpga_fw_day;
	logic [31:0] ptlut_clk_config_word;
	logic [4:0] ptlut_db_inp_del [71:0];
	logic [4:0] ptlut_db_out_del [71:0];
	logic [4:0] ptlut_inp_clk_del;
	logic [4:0] ptlut_db_inp_del_rb [71:0];
	logic [4:0] ptlut_db_out_del_rb [71:0];
	logic ptlut_clk_rst;
	logic ptlut_chips_rst;
	logic ptlut_mrs_cmd;
	logic ptlut_write_cmd;
	logic ptlut_read_cmd;
	logic ptlut_dbdel_clk_en;
	logic ptlut_dbdel_ld;
	logic ptlut_dbdel_rst;
	logic [11:0] ptlut_wr_term_count;
	logic [11:0] ptlut_rd_term_count;
	logic [5:0] ptlut_wr_latency;
	logic [5:0] ptlut_rd_latency;
	logic ptlut_wr_phase_shift;
	logic ptlut_rd_phase_shift;
	logic [4:0] ptlut_dpm_wr_del;
	logic [4:0] ptlut_wr_quad_del;
	logic [4:0] ptlut_rd_quad_del;
	logic ptlut_refresh_en;
	logic [2:0] ptlut_rd_bank_timeout;
	logic [2:0] ptlut_refresh_bank_timout;
	logic [2:0] ptlut_core_rq_mask;
	logic ptlut_busy;
	logic [7:0] ptlut_delay_ctl_locked;
	logic [6:0] th_window;
	logic [3:0] delay_two_mu;
	logic single_en;
	logic two_mu_en;
	logic low_th_promote;
	logic use_rpc;
	logic [6:0] th_window_z0;
	logic two_st_tight_timing;
	logic [25:0] csc_rate_lct [5:0] [9:1];
	logic [25:0] csc_rate_track [2:0];
	logic [7:0] daq_l1a_del;
	logic [2:0] daq_l1a_window;
	logic [7:0] daq_valor_delay;
	logic [2:0] daq_valor_window;
	logic [11:0] daq_bxn_offset;
	logic [15:0] daq_brd_id;
	logic daq_stress_en;
	logic daq_amc13_easy_en;
	logic daq_report_wo_track;
	logic [2:0] daq_rpc_late_by;
	logic [7:0] daq_amc13_timeout_cnt;
	logic [10:0] daq_oos_cnt;
	logic [10:0] daq_bsy_cnt;
	logic [10:0] daq_wof_cnt;
	logic [10:0] daq_rdy_cnt;
	logic [10:0] daq_ill_cnt;
	logic [3:0] daq_tts_state;
	logic amc13_ready_state;
	logic amc13_easy_triggered;
	logic [15:0] amc13_not_ready_cnt;
	logic [15:0] amc13_fifo_full_cnt;
	logic [9:1] use_bc0_ch1 [5:0];
	logic [9:1] en_auto_bc0_ch1 [5:0];
	logic [15:0] usrclk_unlock_cnt;
	logic [31:0] dbg_jtag_length;
	logic [31:0] dbg_jtag_tms;
	logic [31:0] dbg_jtag_tdi;
	logic [31:0] dbg_jtag_tdo;
	logic dbg_jtag_enable;

	modport in
	(
		input gth_rst,
		input inject_test_data,
		input spy_mem_rst,
		input gth_rx_buf_rst,
		input latency_test_en,
		input daq_rst,
		input force_oos,
		input mpc_links_hr_en,
		output csc_link_id,
		output csc_link_id_n,
		output cppf_link_id,
		output cppf_crc_match,
		input csc_fiber_en,
		input csc_fiber_en_n,
		input cppf_fiber_en,
		input ge11_fiber_en,
		output csc_auto_delay,
		output csc_auto_delay_id1,
		output csc_auto_delay_n,
		input csc_manual_delay,
		input csc_manual_delay_id1,
		input csc_manual_delay_n,
		input endcap,
		input sector,
		input spy_data_delay,
		input spy_write_at_l1a,
		input spy_write_at_stub,
		input spy_write_at_rank,
		input af_en,
		input tst_data_inj_en,
		input tst_data_inj_on_mpc_inj_cmd,
		input gth_prbs_mode,
		input af_ttc_bc0_delay,
		input gmt_link_comma_delay,
		input cppf_ttc_bc0_delay,
		output csc_alg_out_range,
		output csc_alg_out_range_id1,
		output csc_alg_out_range_n,
		output csc_bc0_period_err,
		output csc_bc0_period_err_id1,
		output csc_bc0_period_err_n,
		output csc_crc_err,
		output csc_crc_err_n,
		output csc_tst_pat_err,
		output csc_tst_pat_err_n,
		output spy_current_addr,
		output abs_time_cnt,
		output core_fpga_fw_sec,
		output core_fpga_fw_min,
		output core_fpga_fw_hour,
		output core_fpga_fw_year,
		output core_fpga_fw_month,
		output core_fpga_fw_day,
		input ptlut_clk_config_word,
		input ptlut_db_inp_del,
		input ptlut_db_out_del,
		input ptlut_inp_clk_del,
		output ptlut_db_inp_del_rb,
		output ptlut_db_out_del_rb,
		input ptlut_clk_rst,
		input ptlut_chips_rst,
		input ptlut_mrs_cmd,
		input ptlut_write_cmd,
		input ptlut_read_cmd,
		input ptlut_dbdel_clk_en,
		input ptlut_dbdel_ld,
		input ptlut_dbdel_rst,
		input ptlut_wr_term_count,
		input ptlut_rd_term_count,
		input ptlut_wr_latency,
		input ptlut_rd_latency,
		input ptlut_wr_phase_shift,
		input ptlut_rd_phase_shift,
		input ptlut_dpm_wr_del,
		input ptlut_wr_quad_del,
		input ptlut_rd_quad_del,
		input ptlut_refresh_en,
		input ptlut_rd_bank_timeout,
		input ptlut_refresh_bank_timout,
		input ptlut_core_rq_mask,
		output ptlut_busy,
		output ptlut_delay_ctl_locked,
		input th_window,
		input delay_two_mu,
		input single_en,
		input two_mu_en,
		input low_th_promote,
		input use_rpc,
		input th_window_z0,
		input two_st_tight_timing,
		output csc_rate_lct,
		output csc_rate_track,
		input daq_l1a_del,
		input daq_l1a_window,
		input daq_valor_delay,
		input daq_valor_window,
		input daq_bxn_offset,
		input daq_brd_id,
		input daq_stress_en,
		input daq_amc13_easy_en,
		input daq_report_wo_track,
		input daq_rpc_late_by,
		output daq_amc13_timeout_cnt,
		output daq_oos_cnt,
		output daq_bsy_cnt,
		output daq_wof_cnt,
		output daq_rdy_cnt,
		output daq_ill_cnt,
		output daq_tts_state,
		output amc13_ready_state,
		output amc13_easy_triggered,
		output amc13_not_ready_cnt,
		output amc13_fifo_full_cnt,
		input use_bc0_ch1,
		input en_auto_bc0_ch1,
		output usrclk_unlock_cnt,
		input dbg_jtag_length,
		input dbg_jtag_tms,
		input dbg_jtag_tdi,
		output dbg_jtag_tdo,
		input dbg_jtag_enable
	);

	modport out
	(
		output gth_rst,
		output inject_test_data,
		output spy_mem_rst,
		output gth_rx_buf_rst,
		output latency_test_en,
		output daq_rst,
		output force_oos,
		output mpc_links_hr_en,
		input csc_link_id,
		input csc_link_id_n,
		input cppf_link_id,
		input cppf_crc_match,
		output csc_fiber_en,
		output csc_fiber_en_n,
		output cppf_fiber_en,
		output ge11_fiber_en,
		input csc_auto_delay,
		input csc_auto_delay_id1,
		input csc_auto_delay_n,
		output csc_manual_delay,
		output csc_manual_delay_id1,
		output csc_manual_delay_n,
		output endcap,
		output sector,
		output spy_data_delay,
		output spy_write_at_l1a,
		output spy_write_at_stub,
		output spy_write_at_rank,
		output af_en,
		output tst_data_inj_en,
		output tst_data_inj_on_mpc_inj_cmd,
		output gth_prbs_mode,
		output af_ttc_bc0_delay,
		output gmt_link_comma_delay,
		output cppf_ttc_bc0_delay,
		input csc_alg_out_range,
		input csc_alg_out_range_id1,
		input csc_alg_out_range_n,
		input csc_bc0_period_err,
		input csc_bc0_period_err_id1,
		input csc_bc0_period_err_n,
		input csc_crc_err,
		input csc_crc_err_n,
		input csc_tst_pat_err,
		input csc_tst_pat_err_n,
		input spy_current_addr,
		input abs_time_cnt,
		input core_fpga_fw_sec,
		input core_fpga_fw_min,
		input core_fpga_fw_hour,
		input core_fpga_fw_year,
		input core_fpga_fw_month,
		input core_fpga_fw_day,
		output ptlut_clk_config_word,
		output ptlut_db_inp_del,
		output ptlut_db_out_del,
		output ptlut_inp_clk_del,
		input ptlut_db_inp_del_rb,
		input ptlut_db_out_del_rb,
		output ptlut_clk_rst,
		output ptlut_chips_rst,
		output ptlut_mrs_cmd,
		output ptlut_write_cmd,
		output ptlut_read_cmd,
		output ptlut_dbdel_clk_en,
		output ptlut_dbdel_ld,
		output ptlut_dbdel_rst,
		output ptlut_wr_term_count,
		output ptlut_rd_term_count,
		output ptlut_wr_latency,
		output ptlut_rd_latency,
		output ptlut_wr_phase_shift,
		output ptlut_rd_phase_shift,
		output ptlut_dpm_wr_del,
		output ptlut_wr_quad_del,
		output ptlut_rd_quad_del,
		output ptlut_refresh_en,
		output ptlut_rd_bank_timeout,
		output ptlut_refresh_bank_timout,
		output ptlut_core_rq_mask,
		input ptlut_busy,
		input ptlut_delay_ctl_locked,
		output th_window,
		output delay_two_mu,
		output single_en,
		output two_mu_en,
		output low_th_promote,
		output use_rpc,
		output th_window_z0,
		output two_st_tight_timing,
		input csc_rate_lct,
		input csc_rate_track,
		output daq_l1a_del,
		output daq_l1a_window,
		output daq_valor_delay,
		output daq_valor_window,
		output daq_bxn_offset,
		output daq_brd_id,
		output daq_stress_en,
		output daq_amc13_easy_en,
		output daq_report_wo_track,
		output daq_rpc_late_by,
		input daq_amc13_timeout_cnt,
		input daq_oos_cnt,
		input daq_bsy_cnt,
		input daq_wof_cnt,
		input daq_rdy_cnt,
		input daq_ill_cnt,
		input daq_tts_state,
		input amc13_ready_state,
		input amc13_easy_triggered,
		input amc13_not_ready_cnt,
		input amc13_fifo_full_cnt,
		output use_bc0_ch1,
		output en_auto_bc0_ch1,
		input usrclk_unlock_cnt,
		output dbg_jtag_length,
		output dbg_jtag_tms,
		output dbg_jtag_tdi,
		input dbg_jtag_tdo,
		output dbg_jtag_enable
	);

endinterface
`endif
