# This code was automatically generated by FPGA MGT Builder
# Timestamp: 2022-09-15 16:14:34.006
# User: madorsky
# FPGA MGT builder homepage: <link>

set_property LOC BD39 [get_ports refclk_p[ 0]]; # name: 120_0 156.25 MHz
set_property LOC BB39 [get_ports refclk_p[ 1]]; # name: 121_0 156.25 MHz
set_property LOC AY39 [get_ports refclk_p[ 2]]; # name: 122_0 156.25 MHz
set_property LOC AV39 [get_ports refclk_p[ 3]]; # name: 123_0 156.25 MHz
set_property LOC AT39 [get_ports refclk_p[ 4]]; # name: 124_0 156.25 MHz
set_property LOC AP39 [get_ports refclk_p[ 5]]; # name: 125_0 156.25 MHz
set_property LOC AM39 [get_ports refclk_p[ 6]]; # name: 126_0 156.25 MHz
set_property LOC AJ41 [get_ports refclk_p[ 7]]; # name: 127_0 156.25 MHz
set_property LOC AE41 [get_ports refclk_p[ 8]]; # name: 128_0 156.25 MHz
set_property LOC AA41 [get_ports refclk_p[ 9]]; # name: 129_0 156.25 MHz
set_property LOC  W41 [get_ports refclk_p[10]]; # name: 130_0 156.25 MHz
set_property LOC  U41 [get_ports refclk_p[11]]; # name: 131_0 156.25 MHz
set_property LOC  R41 [get_ports refclk_p[12]]; # name: 132_0 156.25 MHz
set_property LOC  N41 [get_ports refclk_p[13]]; # name: 133_0 156.25 MHz
set_property LOC  L41 [get_ports refclk_p[14]]; # name: 134_0 156.25 MHz
set_property LOC  J41 [get_ports refclk_p[15]]; # name: 135_0 156.25 MHz
set_property LOC BD13 [get_ports refclk_p[16]]; # name: 220_0 156.25 MHz
set_property LOC BB13 [get_ports refclk_p[17]]; # name: 221_0 156.25 MHz
set_property LOC AY13 [get_ports refclk_p[18]]; # name: 222_0 156.25 MHz
set_property LOC AV13 [get_ports refclk_p[19]]; # name: 223_0 156.25 MHz
set_property LOC AT13 [get_ports refclk_p[20]]; # name: 224_0 156.25 MHz
set_property LOC AP13 [get_ports refclk_p[21]]; # name: 225_0 156.25 MHz
set_property LOC AM13 [get_ports refclk_p[22]]; # name: 226_0 156.25 MHz
set_property LOC AJ11 [get_ports refclk_p[23]]; # name: 227_0 156.25 MHz
set_property LOC AE11 [get_ports refclk_p[24]]; # name: 228_0 156.25 MHz
set_property LOC AA11 [get_ports refclk_p[25]]; # name: 229_0 156.25 MHz
set_property LOC  W11 [get_ports refclk_p[26]]; # name: 230_0 156.25 MHz
set_property LOC  U11 [get_ports refclk_p[27]]; # name: 231_0 156.25 MHz
set_property LOC  R11 [get_ports refclk_p[28]]; # name: 232_0 156.25 MHz
set_property LOC  N11 [get_ports refclk_p[29]]; # name: 233_0 156.25 MHz
set_property LOC  L11 [get_ports refclk_p[30]]; # name: 234_0 156.25 MHz
set_property LOC  J11 [get_ports refclk_p[31]]; # name: 235_0 156.25 MHz
create_clock -period 6.400 -name refclk_p0  [get_ports refclk_p[ 0]];
create_clock -period 6.400 -name refclk_p1  [get_ports refclk_p[ 1]];
create_clock -period 6.400 -name refclk_p2  [get_ports refclk_p[ 2]];
create_clock -period 6.400 -name refclk_p3  [get_ports refclk_p[ 3]];
create_clock -period 6.400 -name refclk_p4  [get_ports refclk_p[ 4]];
create_clock -period 6.400 -name refclk_p5  [get_ports refclk_p[ 5]];
create_clock -period 6.400 -name refclk_p6  [get_ports refclk_p[ 6]];
create_clock -period 6.400 -name refclk_p7  [get_ports refclk_p[ 7]];
create_clock -period 6.400 -name refclk_p8  [get_ports refclk_p[ 8]];
create_clock -period 6.400 -name refclk_p9  [get_ports refclk_p[ 9]];
create_clock -period 6.400 -name refclk_p10 [get_ports refclk_p[10]];
create_clock -period 6.400 -name refclk_p11 [get_ports refclk_p[11]];
create_clock -period 6.400 -name refclk_p12 [get_ports refclk_p[12]];
create_clock -period 6.400 -name refclk_p13 [get_ports refclk_p[13]];
create_clock -period 6.400 -name refclk_p14 [get_ports refclk_p[14]];
create_clock -period 6.400 -name refclk_p15 [get_ports refclk_p[15]];
create_clock -period 6.400 -name refclk_p16 [get_ports refclk_p[16]];
create_clock -period 6.400 -name refclk_p17 [get_ports refclk_p[17]];
create_clock -period 6.400 -name refclk_p18 [get_ports refclk_p[18]];
create_clock -period 6.400 -name refclk_p19 [get_ports refclk_p[19]];
create_clock -period 6.400 -name refclk_p20 [get_ports refclk_p[20]];
create_clock -period 6.400 -name refclk_p21 [get_ports refclk_p[21]];
create_clock -period 6.400 -name refclk_p22 [get_ports refclk_p[22]];
create_clock -period 6.400 -name refclk_p23 [get_ports refclk_p[23]];
create_clock -period 6.400 -name refclk_p24 [get_ports refclk_p[24]];
create_clock -period 6.400 -name refclk_p25 [get_ports refclk_p[25]];
create_clock -period 6.400 -name refclk_p26 [get_ports refclk_p[26]];
create_clock -period 6.400 -name refclk_p27 [get_ports refclk_p[27]];
create_clock -period 6.400 -name refclk_p28 [get_ports refclk_p[28]];
create_clock -period 6.400 -name refclk_p29 [get_ports refclk_p[29]];
create_clock -period 6.400 -name refclk_p30 [get_ports refclk_p[30]];
create_clock -period 6.400 -name refclk_p31 [get_ports refclk_p[31]];
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p0 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p1 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p2 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p3 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p4 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p5 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p6 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p7 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p8 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p9 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p11] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p12] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p13] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p14] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p15] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p16] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p17] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p18] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p19] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p20] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p21] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p22] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p23] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p24] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p25] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p26] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p27] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p28] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p29] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p30] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p31] -asynchronous
set_property LOC GTYE4_CHANNEL_X0Y1  [get_cells */quad_loop[ 0].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y2  [get_cells */quad_loop[ 0].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y3  [get_cells */quad_loop[ 0].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y5  [get_cells */quad_loop[ 1].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y6  [get_cells */quad_loop[ 1].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y7  [get_cells */quad_loop[ 1].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y8  [get_cells */quad_loop[ 2].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y9  [get_cells */quad_loop[ 2].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y10 [get_cells */quad_loop[ 2].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y11 [get_cells */quad_loop[ 2].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y12 [get_cells */quad_loop[ 3].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y13 [get_cells */quad_loop[ 3].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y14 [get_cells */quad_loop[ 3].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y15 [get_cells */quad_loop[ 3].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y16 [get_cells */quad_loop[ 4].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y17 [get_cells */quad_loop[ 4].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y18 [get_cells */quad_loop[ 4].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y19 [get_cells */quad_loop[ 4].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y20 [get_cells */quad_loop[ 5].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y21 [get_cells */quad_loop[ 5].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y22 [get_cells */quad_loop[ 5].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y23 [get_cells */quad_loop[ 5].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y24 [get_cells */quad_loop[ 6].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y25 [get_cells */quad_loop[ 6].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y26 [get_cells */quad_loop[ 6].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y27 [get_cells */quad_loop[ 6].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y28 [get_cells */quad_loop[ 7].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y29 [get_cells */quad_loop[ 7].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y30 [get_cells */quad_loop[ 7].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y31 [get_cells */quad_loop[ 7].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y32 [get_cells */quad_loop[ 8].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y33 [get_cells */quad_loop[ 8].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y34 [get_cells */quad_loop[ 8].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y35 [get_cells */quad_loop[ 8].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y36 [get_cells */quad_loop[ 9].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y37 [get_cells */quad_loop[ 9].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y38 [get_cells */quad_loop[ 9].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y39 [get_cells */quad_loop[ 9].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y40 [get_cells */quad_loop[10].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y41 [get_cells */quad_loop[10].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y42 [get_cells */quad_loop[10].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y43 [get_cells */quad_loop[10].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y44 [get_cells */quad_loop[11].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y45 [get_cells */quad_loop[11].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y46 [get_cells */quad_loop[11].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y47 [get_cells */quad_loop[11].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y48 [get_cells */quad_loop[12].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y49 [get_cells */quad_loop[12].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y50 [get_cells */quad_loop[12].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y51 [get_cells */quad_loop[12].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y52 [get_cells */quad_loop[13].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y53 [get_cells */quad_loop[13].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y54 [get_cells */quad_loop[13].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y55 [get_cells */quad_loop[13].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y56 [get_cells */quad_loop[14].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y57 [get_cells */quad_loop[14].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y58 [get_cells */quad_loop[14].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y59 [get_cells */quad_loop[14].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y60 [get_cells */quad_loop[15].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y61 [get_cells */quad_loop[15].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y62 [get_cells */quad_loop[15].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y63 [get_cells */quad_loop[15].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y0  [get_cells */quad_loop[16].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y1  [get_cells */quad_loop[16].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y2  [get_cells */quad_loop[16].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y3  [get_cells */quad_loop[16].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y4  [get_cells */quad_loop[17].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y5  [get_cells */quad_loop[17].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y6  [get_cells */quad_loop[17].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y7  [get_cells */quad_loop[17].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y8  [get_cells */quad_loop[18].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y9  [get_cells */quad_loop[18].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y10 [get_cells */quad_loop[18].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y11 [get_cells */quad_loop[18].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y12 [get_cells */quad_loop[19].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y13 [get_cells */quad_loop[19].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y14 [get_cells */quad_loop[19].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y15 [get_cells */quad_loop[19].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y16 [get_cells */quad_loop[20].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y17 [get_cells */quad_loop[20].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y18 [get_cells */quad_loop[20].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y19 [get_cells */quad_loop[20].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y20 [get_cells */quad_loop[21].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y21 [get_cells */quad_loop[21].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y22 [get_cells */quad_loop[21].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y23 [get_cells */quad_loop[21].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y24 [get_cells */quad_loop[22].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y25 [get_cells */quad_loop[22].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y26 [get_cells */quad_loop[22].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y27 [get_cells */quad_loop[22].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y28 [get_cells */quad_loop[23].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y29 [get_cells */quad_loop[23].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y30 [get_cells */quad_loop[23].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y31 [get_cells */quad_loop[23].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y32 [get_cells */quad_loop[24].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y33 [get_cells */quad_loop[24].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y34 [get_cells */quad_loop[24].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y35 [get_cells */quad_loop[24].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y36 [get_cells */quad_loop[25].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y37 [get_cells */quad_loop[25].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y38 [get_cells */quad_loop[25].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y39 [get_cells */quad_loop[25].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y40 [get_cells */quad_loop[26].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y41 [get_cells */quad_loop[26].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y42 [get_cells */quad_loop[26].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y43 [get_cells */quad_loop[26].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y44 [get_cells */quad_loop[27].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y45 [get_cells */quad_loop[27].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y46 [get_cells */quad_loop[27].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y47 [get_cells */quad_loop[27].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y48 [get_cells */quad_loop[28].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y49 [get_cells */quad_loop[28].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y50 [get_cells */quad_loop[28].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y51 [get_cells */quad_loop[28].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y52 [get_cells */quad_loop[29].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y53 [get_cells */quad_loop[29].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y54 [get_cells */quad_loop[29].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y55 [get_cells */quad_loop[29].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y56 [get_cells */quad_loop[30].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y57 [get_cells */quad_loop[30].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y58 [get_cells */quad_loop[30].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y59 [get_cells */quad_loop[30].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y60 [get_cells */quad_loop[31].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y61 [get_cells */quad_loop[31].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y62 [get_cells */quad_loop[31].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y63 [get_cells */quad_loop[31].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
create_clock -period 2.550 -name rxclk0_1 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx0
create_clock -period 2.550 -name txclk0_1 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx0
create_clock -period 2.550 -name rxclk0_2 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx1
create_clock -period 2.550 -name txclk0_2 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx1
create_clock -period 2.550 -name rxclk0_3 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx2
create_clock -period 2.550 -name txclk0_3 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx2
create_clock -period 2.550 -name rxclk0_5 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx3
create_clock -period 2.550 -name txclk0_5 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx3
create_clock -period 2.550 -name rxclk0_6 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx4
create_clock -period 2.550 -name txclk0_6 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx4
create_clock -period 2.550 -name rxclk0_7 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx5
create_clock -period 2.550 -name txclk0_7 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx5
create_clock -period 2.550 -name rxclk0_8 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx6
create_clock -period 2.550 -name txclk0_8 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx6
create_clock -period 2.550 -name rxclk0_9 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx7
create_clock -period 2.550 -name txclk0_9 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx7
create_clock -period 2.550 -name rxclk0_10 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx8
create_clock -period 2.550 -name txclk0_10 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx8
create_clock -period 2.550 -name rxclk0_11 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx9
create_clock -period 2.550 -name txclk0_11 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx9
create_clock -period 2.550 -name rxclk0_12 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx10
create_clock -period 2.550 -name txclk0_12 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx10
create_clock -period 2.550 -name rxclk0_13 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx11
create_clock -period 2.550 -name txclk0_13 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx11
create_clock -period 2.550 -name rxclk0_14 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx12
create_clock -period 2.550 -name txclk0_14 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx12
create_clock -period 2.550 -name rxclk0_15 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx13
create_clock -period 2.550 -name txclk0_15 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx13
create_clock -period 2.550 -name rxclk0_16 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx14
create_clock -period 2.550 -name txclk0_16 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx14
create_clock -period 2.550 -name rxclk0_17 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx15
create_clock -period 2.550 -name txclk0_17 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx15
create_clock -period 2.550 -name rxclk0_18 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx16
create_clock -period 2.550 -name txclk0_18 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx16
create_clock -period 2.550 -name rxclk0_19 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx17
create_clock -period 2.550 -name txclk0_19 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx17
create_clock -period 2.550 -name rxclk0_20 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx18
create_clock -period 2.550 -name txclk0_20 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx18
create_clock -period 2.550 -name rxclk0_21 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx19
create_clock -period 2.550 -name txclk0_21 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx19
create_clock -period 2.550 -name rxclk0_22 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx20
create_clock -period 2.550 -name txclk0_22 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx20
create_clock -period 2.550 -name rxclk0_23 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx21
create_clock -period 2.550 -name txclk0_23 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx21
create_clock -period 2.550 -name rxclk0_24 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx22
create_clock -period 2.550 -name txclk0_24 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx22
create_clock -period 2.550 -name rxclk0_25 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx23
create_clock -period 2.550 -name txclk0_25 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx23
create_clock -period 2.550 -name rxclk0_26 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx24
create_clock -period 2.550 -name txclk0_26 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx24
create_clock -period 2.550 -name rxclk0_27 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx25
create_clock -period 2.550 -name txclk0_27 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx25
create_clock -period 2.550 -name rxclk0_28 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx26
create_clock -period 2.550 -name txclk0_28 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx26
create_clock -period 2.550 -name rxclk0_29 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx27
create_clock -period 2.550 -name txclk0_29 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx27
create_clock -period 2.550 -name rxclk0_30 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx28
create_clock -period 2.550 -name txclk0_30 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx28
create_clock -period 2.550 -name rxclk0_31 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx29
create_clock -period 2.550 -name txclk0_31 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx29
create_clock -period 2.550 -name rxclk0_32 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx30
create_clock -period 2.550 -name txclk0_32 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx30
create_clock -period 2.550 -name rxclk0_33 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx31
create_clock -period 2.550 -name txclk0_33 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx31
create_clock -period 2.550 -name rxclk0_34 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx32
create_clock -period 2.550 -name txclk0_34 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx32
create_clock -period 2.550 -name rxclk0_35 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx33
create_clock -period 2.550 -name txclk0_35 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx33
create_clock -period 2.550 -name rxclk0_36 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx34
create_clock -period 2.550 -name txclk0_36 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx34
create_clock -period 2.550 -name rxclk0_37 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx35
create_clock -period 2.550 -name txclk0_37 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx35
create_clock -period 2.550 -name rxclk0_38 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx36
create_clock -period 2.550 -name txclk0_38 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx36
create_clock -period 2.550 -name rxclk0_39 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx37
create_clock -period 2.550 -name txclk0_39 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx37
create_clock -period 2.550 -name rxclk0_40 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx38
create_clock -period 2.550 -name txclk0_40 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx38
create_clock -period 2.550 -name rxclk0_41 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx39
create_clock -period 2.550 -name txclk0_41 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx39
create_clock -period 2.550 -name rxclk0_42 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx40
create_clock -period 2.550 -name txclk0_42 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx40
create_clock -period 2.550 -name rxclk0_43 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx41
create_clock -period 2.550 -name txclk0_43 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx41
create_clock -period 2.550 -name rxclk0_44 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx42
create_clock -period 2.550 -name txclk0_44 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx42
create_clock -period 2.550 -name rxclk0_45 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx43
create_clock -period 2.550 -name txclk0_45 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx43
create_clock -period 2.550 -name rxclk0_46 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx44
create_clock -period 2.550 -name txclk0_46 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx44
create_clock -period 2.550 -name rxclk0_47 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx45
create_clock -period 2.550 -name txclk0_47 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx45
create_clock -period 2.550 -name rxclk0_48 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx46
create_clock -period 2.550 -name txclk0_48 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx46
create_clock -period 2.550 -name rxclk0_49 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx47
create_clock -period 2.550 -name txclk0_49 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx47
create_clock -period 2.550 -name rxclk0_50 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx48
create_clock -period 2.550 -name txclk0_50 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx48
create_clock -period 2.550 -name rxclk0_51 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx49
create_clock -period 2.550 -name txclk0_51 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx49
create_clock -period 2.550 -name rxclk0_52 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx50
create_clock -period 2.550 -name txclk0_52 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx50
create_clock -period 2.550 -name rxclk0_53 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx51
create_clock -period 2.550 -name txclk0_53 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx51
create_clock -period 2.550 -name rxclk0_54 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx52
create_clock -period 2.550 -name txclk0_54 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx52
create_clock -period 2.550 -name rxclk0_55 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx53
create_clock -period 2.550 -name txclk0_55 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx53
create_clock -period 2.550 -name rxclk0_56 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx54
create_clock -period 2.550 -name txclk0_56 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx54
create_clock -period 2.550 -name rxclk0_57 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx55
create_clock -period 2.550 -name txclk0_57 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx55
create_clock -period 2.550 -name rxclk0_58 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx56
create_clock -period 2.550 -name txclk0_58 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx56
create_clock -period 2.550 -name rxclk0_59 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx57
create_clock -period 2.550 -name txclk0_59 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx57
create_clock -period 2.550 -name rxclk0_60 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx58
create_clock -period 2.550 -name txclk0_60 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx58
create_clock -period 2.550 -name rxclk0_61 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx59
create_clock -period 2.550 -name txclk0_61 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx59
create_clock -period 2.550 -name rxclk0_62 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx60
create_clock -period 2.550 -name txclk0_62 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx60
create_clock -period 2.550 -name rxclk0_63 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx61
create_clock -period 2.550 -name txclk0_63 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx61
create_clock -period 2.550 -name rxclk1_0 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx62
create_clock -period 2.550 -name txclk1_0 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx62
create_clock -period 2.550 -name rxclk1_1 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx63
create_clock -period 2.550 -name txclk1_1 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx63
create_clock -period 2.550 -name rxclk1_2 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx64
create_clock -period 2.550 -name txclk1_2 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx64
create_clock -period 2.550 -name rxclk1_3 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx65
create_clock -period 2.550 -name txclk1_3 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx65
create_clock -period 2.550 -name rxclk1_4 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx66
create_clock -period 2.550 -name txclk1_4 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx66
create_clock -period 2.550 -name rxclk1_5 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx67
create_clock -period 2.550 -name txclk1_5 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx67
create_clock -period 2.550 -name rxclk1_6 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx68
create_clock -period 2.550 -name txclk1_6 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx68
create_clock -period 2.550 -name rxclk1_7 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx69
create_clock -period 2.550 -name txclk1_7 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx69
create_clock -period 2.550 -name rxclk1_8 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx70
create_clock -period 2.550 -name txclk1_8 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx70
create_clock -period 2.550 -name rxclk1_9 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx71
create_clock -period 2.550 -name txclk1_9 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx71
create_clock -period 2.550 -name rxclk1_10 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx72
create_clock -period 2.550 -name txclk1_10 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx72
create_clock -period 2.550 -name rxclk1_11 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx73
create_clock -period 2.550 -name txclk1_11 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx73
create_clock -period 2.550 -name rxclk1_12 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx74
create_clock -period 2.550 -name txclk1_12 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx74
create_clock -period 2.550 -name rxclk1_13 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx75
create_clock -period 2.550 -name txclk1_13 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx75
create_clock -period 2.550 -name rxclk1_14 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx76
create_clock -period 2.550 -name txclk1_14 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx76
create_clock -period 2.550 -name rxclk1_15 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx77
create_clock -period 2.550 -name txclk1_15 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx77
create_clock -period 2.550 -name rxclk1_16 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx78
create_clock -period 2.550 -name txclk1_16 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx78
create_clock -period 2.550 -name rxclk1_17 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx79
create_clock -period 2.550 -name txclk1_17 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx79
create_clock -period 2.550 -name rxclk1_18 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx80
create_clock -period 2.550 -name txclk1_18 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx80
create_clock -period 2.550 -name rxclk1_19 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx81
create_clock -period 2.550 -name txclk1_19 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx81
create_clock -period 2.550 -name rxclk1_20 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[21]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx82
create_clock -period 2.550 -name txclk1_20 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[21]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx82
create_clock -period 2.550 -name rxclk1_21 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[21]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx83
create_clock -period 2.550 -name txclk1_21 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[21]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx83
create_clock -period 2.550 -name rxclk1_22 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[21]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx84
create_clock -period 2.550 -name txclk1_22 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[21]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx84
create_clock -period 2.550 -name rxclk1_23 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[21]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx85
create_clock -period 2.550 -name txclk1_23 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[21]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx85
create_clock -period 2.550 -name rxclk1_24 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[22]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx86
create_clock -period 2.550 -name txclk1_24 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[22]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx86
create_clock -period 2.550 -name rxclk1_25 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[22]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx87
create_clock -period 2.550 -name txclk1_25 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[22]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx87
create_clock -period 2.550 -name rxclk1_26 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[22]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx88
create_clock -period 2.550 -name txclk1_26 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[22]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx88
create_clock -period 2.550 -name rxclk1_27 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[22]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx89
create_clock -period 2.550 -name txclk1_27 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[22]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx89
create_clock -period 2.550 -name rxclk1_28 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[23]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx90
create_clock -period 2.550 -name txclk1_28 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[23]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx90
create_clock -period 2.550 -name rxclk1_29 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[23]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx91
create_clock -period 2.550 -name txclk1_29 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[23]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx91
create_clock -period 2.550 -name rxclk1_30 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[23]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx92
create_clock -period 2.550 -name txclk1_30 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[23]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx92
create_clock -period 2.550 -name rxclk1_31 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[23]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx93
create_clock -period 2.550 -name txclk1_31 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[23]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx93
create_clock -period 2.550 -name rxclk1_32 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[24]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx94
create_clock -period 2.550 -name txclk1_32 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[24]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx94
create_clock -period 2.550 -name rxclk1_33 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[24]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx95
create_clock -period 2.550 -name txclk1_33 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[24]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx95
create_clock -period 2.550 -name rxclk1_34 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[24]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx96
create_clock -period 2.550 -name txclk1_34 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[24]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx96
create_clock -period 2.550 -name rxclk1_35 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[24]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx97
create_clock -period 2.550 -name txclk1_35 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[24]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx97
create_clock -period 2.550 -name rxclk1_36 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[25]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx98
create_clock -period 2.550 -name txclk1_36 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[25]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx98
create_clock -period 2.550 -name rxclk1_37 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[25]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx99
create_clock -period 2.550 -name txclk1_37 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[25]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx99
create_clock -period 2.550 -name rxclk1_38 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[25]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx100
create_clock -period 2.550 -name txclk1_38 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[25]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx100
create_clock -period 2.550 -name rxclk1_39 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[25]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx101
create_clock -period 2.550 -name txclk1_39 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[25]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx101
create_clock -period 2.550 -name rxclk1_40 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[26]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx102
create_clock -period 2.550 -name txclk1_40 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[26]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx102
create_clock -period 2.550 -name rxclk1_41 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[26]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx103
create_clock -period 2.550 -name txclk1_41 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[26]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx103
create_clock -period 2.550 -name rxclk1_42 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[26]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx104
create_clock -period 2.550 -name txclk1_42 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[26]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx104
create_clock -period 2.550 -name rxclk1_43 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[26]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx105
create_clock -period 2.550 -name txclk1_43 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[26]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx105
create_clock -period 2.550 -name rxclk1_44 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[27]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx106
create_clock -period 2.550 -name txclk1_44 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[27]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx106
create_clock -period 2.550 -name rxclk1_45 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[27]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx107
create_clock -period 2.550 -name txclk1_45 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[27]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx107
create_clock -period 2.550 -name rxclk1_46 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[27]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx108
create_clock -period 2.550 -name txclk1_46 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[27]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx108
create_clock -period 2.550 -name rxclk1_47 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[27]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx109
create_clock -period 2.550 -name txclk1_47 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[27]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx109
create_clock -period 2.550 -name rxclk1_48 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[28]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx110
create_clock -period 2.550 -name txclk1_48 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[28]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx110
create_clock -period 2.550 -name rxclk1_49 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[28]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx111
create_clock -period 2.550 -name txclk1_49 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[28]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx111
create_clock -period 2.550 -name rxclk1_50 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[28]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx112
create_clock -period 2.550 -name txclk1_50 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[28]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx112
create_clock -period 2.550 -name rxclk1_51 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[28]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx113
create_clock -period 2.550 -name txclk1_51 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[28]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx113
create_clock -period 2.550 -name rxclk1_52 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[29]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx114
create_clock -period 2.550 -name txclk1_52 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[29]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx114
create_clock -period 2.550 -name rxclk1_53 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[29]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx115
create_clock -period 2.550 -name txclk1_53 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[29]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx115
create_clock -period 2.550 -name rxclk1_54 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[29]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx116
create_clock -period 2.550 -name txclk1_54 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[29]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx116
create_clock -period 2.550 -name rxclk1_55 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[29]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx117
create_clock -period 2.550 -name txclk1_55 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[29]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx117
create_clock -period 2.550 -name rxclk1_56 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[30]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx118
create_clock -period 2.550 -name txclk1_56 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[30]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx118
create_clock -period 2.550 -name rxclk1_57 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[30]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx119
create_clock -period 2.550 -name txclk1_57 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[30]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx119
create_clock -period 2.550 -name rxclk1_58 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[30]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx120
create_clock -period 2.550 -name txclk1_58 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[30]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx120
create_clock -period 2.550 -name rxclk1_59 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[30]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx121
create_clock -period 2.550 -name txclk1_59 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[30]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx121
create_clock -period 2.550 -name rxclk1_60 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[31]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_rx122
create_clock -period 2.550 -name txclk1_60 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[31]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # p25g_tx122
create_clock -period 2.550 -name rxclk1_61 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[31]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_rx123
create_clock -period 2.550 -name txclk1_61 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[31]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # p25g_tx123
create_clock -period 2.550 -name rxclk1_62 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[31]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_rx124
create_clock -period 2.550 -name txclk1_62 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[31]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # p25g_tx124
create_clock -period 2.550 -name rxclk1_63 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[31]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_rx125
create_clock -period 2.550 -name txclk1_63 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[31]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # p25g_tx125
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_1] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_1] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_2] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_2] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_3] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_3] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_5] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_5] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_6] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_6] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_7] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_7] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_8] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_8] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_9] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_9] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_11] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_11] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_12] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_12] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_13] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_13] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_14] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_14] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_15] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_15] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_16] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_16] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_17] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_17] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_18] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_18] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_19] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_19] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_20] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_20] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_21] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_21] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_22] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_22] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_23] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_23] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_24] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_24] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_25] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_25] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_26] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_26] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_27] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_27] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_28] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_28] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_29] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_29] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_30] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_30] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_31] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_31] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_32] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_32] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_33] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_33] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_34] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_34] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_35] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_35] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_36] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_36] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_37] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_37] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_38] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_38] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_39] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_39] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_40] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_40] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_41] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_41] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_42] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_42] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_43] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_43] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_44] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_44] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_45] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_45] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_46] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_46] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_47] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_47] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_48] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_48] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_49] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_49] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_50] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_50] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_51] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_51] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_52] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_52] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_53] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_53] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_54] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_54] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_55] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_55] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_56] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_56] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_57] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_57] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_58] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_58] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_59] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_59] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_60] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_60] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_61] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_61] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_62] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_62] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_63] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_63] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_0] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_0] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_1] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_1] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_2] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_2] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_3] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_3] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_4] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_4] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_5] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_5] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_6] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_6] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_7] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_7] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_8] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_8] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_9] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_9] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_11] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_11] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_12] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_12] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_13] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_13] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_14] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_14] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_15] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_15] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_16] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_16] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_17] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_17] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_18] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_18] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_19] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_19] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_20] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_20] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_21] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_21] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_22] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_22] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_23] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_23] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_24] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_24] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_25] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_25] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_26] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_26] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_27] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_27] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_28] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_28] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_29] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_29] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_30] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_30] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_31] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_31] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_32] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_32] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_33] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_33] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_34] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_34] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_35] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_35] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_36] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_36] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_37] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_37] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_38] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_38] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_39] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_39] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_40] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_40] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_41] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_41] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_42] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_42] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_43] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_43] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_44] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_44] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_45] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_45] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_46] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_46] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_47] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_47] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_48] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_48] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_49] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_49] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_50] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_50] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_51] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_51] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_52] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_52] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_53] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_53] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_54] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_54] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_55] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_55] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_56] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_56] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_57] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_57] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_58] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_58] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_59] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_59] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_60] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_60] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_61] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_61] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_62] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_62] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_63] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk1_63] -asynchronous
