// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2022-03-23 23:30:16.585
// User: madorsky
// FPGA MGT builder homepage: <link>

	wire [15:0] mgtxy [0:1][0:3]; // [quad][mgt]
	assign mgtxy[0][0] = 16'ha100;
	assign mgtxy[0][1] = 16'ha101;
	assign mgtxy[0][2] = 16'ha102;
	assign mgtxy[0][3] = 16'ha103;
	assign mgtxy[1][0] = 16'ha104;
	assign mgtxy[1][1] = 16'ha105;
	assign mgtxy[1][2] = 16'ha106;
	assign mgtxy[1][3] = 16'ha107;
