// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2024-10-11 09:31:28.753
// User: patrick
// FPGA MGT builder homepage: https://github.com/madorskya/mgt_builder

`include "drp_interface.sv"
`include "mgt_interfaces.sv"
module GTHE2_COMMON_tux
#(parameter [7:0] qind = 0, parameter [7:0] mind = 0)
(
	drp.in drp_if,
	output        qplloutclk,
	output        qplloutrefclk,
	output        refclkoutmonitor,
	input         drpclk,
	input         qplllockdetclk,
	input         gtrefclk0
);
`include "xymap.sv"
	wire [15:0] XY = mgtxy[qind][mind];
	reg  [31:0] reg_  [ 0: 0];
	wire [31:0] wire_ [ 1: 1];
	initial
	begin
	end
    reg         int_reg_rdy;
    reg  [31:0] drpdo_reg;
    wire        drprdy_mgt;
    wire [31:0] drpdo_mgt;
    reg         drprdy_reg;
    assign drp_if.drprdy = drprdy_reg;
    assign drp_if.drpdo  = drpdo_reg;
    always @(posedge drpclk)
    begin
        drprdy_reg = 1'b0;
		drpdo_reg = 32'h0;
        if (drp_if.int_reg == 1'b1)
        begin
            if (drp_if.drpwe == 1'b1)
            begin
                case (drp_if.drpaddr)

                    9'd0: reg_[0] = drp_if.drpdi;
                endcase
                drprdy_reg = 1'b1;
            end
            else
            begin
                case (drp_if.drpaddr)

                    9'd0: drpdo_reg = reg_[0];
                    9'd1: drpdo_reg = wire_[1];
                    9'h1ff: drpdo_reg = XY; // each MGT reports its XY
                endcase
                drprdy_reg = 1'b1;
            end
        end

        if (drprdy_mgt == 1'b1)
        begin
            drpdo_reg = drpdo_mgt;
            drprdy_reg = 1'b1;
        end
    end

	GTHE2_COMMON GTHE2_COMMON_inst
	(
		.QPLLOUTCLK                 (qplloutclk                ),
		.QPLLOUTREFCLK              (qplloutrefclk             ),
		.REFCLKOUTMONITOR           (refclkoutmonitor          ),
		.DRPADDR                    (drp_if.drpaddr            ),
		.DRPCLK                     (drpclk                    ),
		.DRPDI                      (drp_if.drpdi [15:0]),
		.DRPDO                      (drpdo_mgt [15:0]),
		.DRPEN                      (drp_if.drpen              ),
		.DRPRDY                     (drprdy_mgt),
		.DRPWE                      (drp_if.drpwe              ),
		.QPLLDMONITOR               (),
		.BGBYPASSB                  (1'b1),
		.BGMONITORENB               (1'b1),
		.BGPDB                      (1'b1),
		.BGRCALOVRD                 (5'b11111),
		.BGRCALOVRDENB              (1'b1),
		.PMARSVD                    (8'b0),
		.PMARSVDOUT                 (),
		.QPLLFBCLKLOST              (wire_[1][ 0: 0]),
		.QPLLLOCK                   (wire_[1][ 1: 1]),
		.QPLLLOCKDETCLK             (qplllockdetclk            ),
		.QPLLLOCKEN                 (1'b1),
		.QPLLOUTRESET               (1'b0),
		.QPLLPD                     ( reg_[0][ 0: 0]),
		.QPLLREFCLKLOST             (wire_[1][ 2: 2]),
		.QPLLREFCLKSEL              (3'b001),
		.QPLLRESET                  ( reg_[0][ 1: 1]),
		.QPLLRSVD1                  (16'h0),
		.QPLLRSVD2                  (5'b11111),
		.RCALENB                    (1'b1),
		.GTGREFCLK                  (1'b0),
		.GTNORTHREFCLK0             (1'b0),
		.GTNORTHREFCLK1             (1'b0),
		.GTREFCLK0                  (gtrefclk0                 ),
		.GTREFCLK1                  (1'b0),
		.GTSOUTHREFCLK0             (1'b0),
		.GTSOUTHREFCLK1             (1'b0)
	);
endmodule
