// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2021-01-30 10:52:57.958
// User: madorsky
// FPGA MGT builder homepage: <link>

	wire [15:0] mgtxy [0:0][0:3]; // [quad][mgt]
	assign mgtxy[0][1] = 16'ha009;
	assign mgtxy[0][3] = 16'ha011;
