// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-12-07 11:24:55.285
// User: madorsky
// FPGA MGT builder homepage: <link>

`include "drp_interface.sv"
`include "mgt_gth_interfaces.sv"
module apex_ku15p_gth_serial_io
(
	drp.in drp_gth_fif,
	input drpclk,
	input [5:0] refclk_p,
	input [5:0] refclk_n,
	mgt_gth_rx.in tcds_rx [3:0],
	mgt_gth_tx.in tcds_tx [3:0],
	output TCDS_2_mmcm_clk,
    output refclk5,
    output refclk5_bufg
);
	localparam quadn = 1;
	drp #(.AW(13)) drp_gth_qif [quadn-1:0]();
	drp_mux_fpga #(.N(quadn), .AW_QUAD(13)) drpm (drp_gth_qif, drp_gth_fif, drpclk);

	mgt_gth_tx mgt_gth_tx_if [quadn-1:0][3:0]();
	mgt_gth_rx mgt_gth_rx_if [quadn-1:0][3:0]();
	wire        mgt_txlatclk ;
	wire [ 3:0] mgt_txusrclk [quadn-1:0];
	wire        com_gtrefclk00 [quadn-1:0];
	wire        com_gtrefclk01 [quadn-1:0];
	wire [5:0] refclk;
	wire [5:0] refclk_b;
	genvar gi;
	generate
		for (gi = 0; gi < quadn; gi++)
		begin: quad_loop
			GTHE4_QUAD #(.ind(gi)) GTHE4_QUAD_inst
			(
				.drp_gth_qif (drp_gth_qif [gi]),
				.drpclk (drpclk),
				.mgt_gth_tx_if (mgt_gth_tx_if [gi]),
				.mgt_gth_rx_if (mgt_gth_rx_if [gi]),
				.mgt_txlatclk               (mgt_txlatclk              ),
				.mgt_txusrclk               (mgt_txusrclk               [gi]),
				.com_gtrefclk00             (com_gtrefclk00             [gi]),
				.com_gtrefclk01             (com_gtrefclk01             [gi])
			);
		end
		for (gi = 0; gi < 6; gi++)
		begin: refclk_loop
			IBUFDS_GTE4 #
			(
				.REFCLK_EN_TX_PATH  (1'b0),
				.REFCLK_HROW_CK_SEL (2'b00),
				.REFCLK_ICNTL_RX    (2'b00)
			) 
			refclk_buf
			(
				.I     (refclk_p [gi]),
				.IB    (refclk_n [gi]),
				.CEB   (1'b0),
				.O     (refclk   [gi]),
				.ODIV2 (refclk_b [gi])
			);
		end
	endgenerate
	assign_mgt_gth_rx ari0 (mgt_gth_rx_if [0][0], tcds_rx [0]);
	assign_mgt_gth_tx ati0 (mgt_gth_tx_if [0][0], tcds_tx [0]);
	assign_mgt_gth_rx ari1 (mgt_gth_rx_if [0][1], tcds_rx [1]);
	assign_mgt_gth_tx ati1 (mgt_gth_tx_if [0][1], tcds_tx [1]);
	assign_mgt_gth_rx ari2 (mgt_gth_rx_if [0][2], tcds_rx [2]);
	assign_mgt_gth_tx ati2 (mgt_gth_tx_if [0][2], tcds_tx [2]);
	assign_mgt_gth_rx ari3 (mgt_gth_rx_if [0][3], tcds_rx [3]);
	assign_mgt_gth_tx ati3 (mgt_gth_tx_if [0][3], tcds_tx [3]);
	assign com_gtrefclk00 [0] = refclk [2]; // tcds_tx 0
	assign com_gtrefclk00 [0] = refclk [2]; // tcds_tx 1
	assign com_gtrefclk00 [0] = refclk [2]; // tcds_tx 2
	assign com_gtrefclk00 [0] = refclk [2]; // tcds_tx 3
	bufg_gt_tux TCDS_2_inst (.O(TCDS_2_mmcm_clk), .I(mgt_gth_tx_if[0][0].txoutclk));
	assign mgt_txusrclk[0][0] = TCDS_2_mmcm_clk; // tcds_tx0
	assign mgt_txusrclk[0][1] = TCDS_2_mmcm_clk; // tcds_tx1
	assign mgt_txusrclk[0][2] = TCDS_2_mmcm_clk; // tcds_tx2
	assign mgt_txusrclk[0][3] = TCDS_2_mmcm_clk; // tcds_tx3
    assign refclk5 = refclk [5];
    assign refclk5_bufg = refclk_b [5];

endmodule
