// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-11-04 11:46:15.4
// User: madorsky
// FPGA MGT builder homepage: <link>

`include "drp_interface.sv"
`include "mgt_interfaces.sv"
module apex_ku15p_serial_io
(
	drp.in drp_fif,
	input drpclk,
	input [5:0] refclk_p,
	input [5:0] refclk_n,
	mgt_rx.in tcds_rx [0:0],
	mgt_tx.in tcds_tx [0:0],
	output TCDS_4_mmcm_clk
);
	localparam quadn = 1;
	drp #(.AW(12)) drp_qif [quadn-1:0]();
	drp_mux_fpga #(.N(quadn), .AW_QUAD(12)) drpm (drp_qif, drp_fif, drpclk);

	mgt_tx mgt_tx_if [quadn-1:0][3:0]();
	mgt_rx mgt_rx_if [quadn-1:0][3:0]();
	wire [ 3:0] mgt_qpll0clk [quadn-1:0];
	wire [ 3:0] mgt_qpll1clk [quadn-1:0];
	wire [ 3:0] mgt_qpll0refclk [quadn-1:0];
	wire [ 3:0] mgt_qpll1refclk [quadn-1:0];
	wire        mgt_cplllockdetclk ;
	wire        mgt_dmonitorclk ;
	wire [ 3:0] mgt_txusrclk [quadn-1:0];
	wire [ 3:0] mgt_txusrclk2 [quadn-1:0];
	wire        mgt_txlatclk ;
	wire [ 1:0] mgt_txbufstatus [quadn-1:0][3:0];
	wire [ 3:0] mgt_txoutclk [quadn-1:0];
	wire [ 3:0] mgt_rxphaligndone [quadn-1:0];
	wire        mgt_rxsyncallin ;
	wire        com_gtrefclk00 ;
	wire        com_gtrefclk01 ;
	wire        com_qpll0outclk ;
	wire        com_qpll1outclk ;
	wire        com_qpll0outrefclk ;
	wire        com_qpll1outrefclk ;
	wire        com_qpll0lockdetclk ;
	wire        com_qpll1lockdetclk ;
	wire        com_qpll0outrefclk ;
	wire        com_qpll1outrefclk ;
	wire [5:0] refclk;
	genvar gi;
	generate
		for (gi = 0; gi < quadn; gi++)
		begin: quad_loop
			GTHE4_QUAD #(.ind(gi)) GTHE4_QUAD_inst
			(
				.drp_qif (drp_qif [gi]),
				.drpclk (drpclk),
				.mgt_tx_if (mgt_tx_if [gi]),
				.mgt_rx_if (mgt_rx_if [gi]),
				.mgt_qpll0clk               (mgt_qpll0clk               [gi]),
				.mgt_qpll1clk               (mgt_qpll1clk               [gi]),
				.mgt_qpll0refclk            (mgt_qpll0refclk            [gi]),
				.mgt_qpll1refclk            (mgt_qpll1refclk            [gi]),
				.mgt_cplllockdetclk         (mgt_cplllockdetclk        ),
				.mgt_dmonitorclk            (mgt_dmonitorclk           ),
				.mgt_txusrclk               (mgt_txusrclk               [gi]),
				.mgt_txusrclk2              (mgt_txusrclk2              [gi]),
				.mgt_txlatclk               (mgt_txlatclk              ),
				.mgt_txbufstatus            (mgt_txbufstatus            [gi]),
				.mgt_txoutclk               (mgt_txoutclk               [gi]),
				.mgt_rxphaligndone          (mgt_rxphaligndone          [gi]),
				.mgt_rxsyncallin            (mgt_rxsyncallin           ),
				.com_gtrefclk00             (com_gtrefclk00            ),
				.com_gtrefclk01             (com_gtrefclk01            ),
				.com_qpll0outclk            (com_qpll0outclk           ),
				.com_qpll1outclk            (com_qpll1outclk           ),
				.com_qpll0outrefclk         (com_qpll0outrefclk        ),
				.com_qpll1outrefclk         (com_qpll1outrefclk        ),
				.com_qpll0lockdetclk        (com_qpll0lockdetclk       ),
				.com_qpll1lockdetclk        (com_qpll1lockdetclk       ),
				.com_qpll0outrefclk         (com_qpll0outrefclk        ),
				.com_qpll1outrefclk         (com_qpll1outrefclk        )
			);
		end
		for (gi = 0; gi < 6; gi++)
		begin: refclk_loop
			IBUFDS_GTE4 #
			(
				.REFCLK_EN_TX_PATH  (1'b0),
				.REFCLK_HROW_CK_SEL (2'b00),
				.REFCLK_ICNTL_RX    (2'b00)
			) 
			refclk_buf
			(
				.I     (refclk_p [gi]),
				.IB    (refclk_n [gi]),
				.CEB   (1'b0),
				.O     (refclk   [gi]),
				.ODIV2 ()
			);
		end
	endgenerate
	assign_mgt_rx ari0 (mgt_rx_if [0][0], tcds_rx [0]);
	assign_mgt_tx ati1 (mgt_tx_if [0][1], tcds_tx [0]);
	assign com_gtrefclk00 [0] = refclk [4]; // tcds_rx 0
	assign com_gtrefclk00 [0] = refclk [4]; // tcds_tx 0
	TCDS_mmcm TCDS_4_inst (.O(TCDS_4_mmcm_clk), .I(mgt_tx_if[0][1].txoutclk));
	assign mgt_txusrclk[0][1] = TCDS_4_mmcm_clk; // tcds_tx0
endmodule
