# This code was automatically generated by FPGA MGT Builder
# Timestamp: 2020-11-06 10:51:37.69
# User: madorsky
# FPGA MGT builder homepage: <link>

set_property LOC  V32 [get_ports refclk_p[ 0]]; # name: 131_0 160.3144 MHz
set_property LOC  U30 [get_ports refclk_p[ 1]]; # name: 131_1 322.265625 MHz
set_property LOC  M32 [get_ports refclk_p[ 2]]; # name: 134_0 160.3144 MHz
set_property LOC  L30 [get_ports refclk_p[ 3]]; # name: 134_1 322.265625 MHz
set_property LOC AD32 [get_ports refclk_p[ 4]]; # name: 128_0 160.3144 MHz
set_property LOC AC30 [get_ports refclk_p[ 5]]; # name: 128_1 322.265625 MHz
create_clock -period 6.238 -name refclk_p0  [get_ports refclk_p[ 0]];
create_clock -period 3.103 -name refclk_p1  [get_ports refclk_p[ 1]];
create_clock -period 6.238 -name refclk_p2  [get_ports refclk_p[ 2]];
create_clock -period 3.103 -name refclk_p3  [get_ports refclk_p[ 3]];
create_clock -period 6.238 -name refclk_p4  [get_ports refclk_p[ 4]];
create_clock -period 3.103 -name refclk_p5  [get_ports refclk_p[ 5]];
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p0 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p1 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p2 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p3 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p4 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p5 ] -asynchronous
set_property LOC GTYE4_CHANNEL_X0Y0  [get_cells */quad_loop[ 0].GTTE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y1  [get_cells */quad_loop[ 0].GTTE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
create_clock -period 3.100 -name rxclk0_0 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # tcds_rx0
create_clock -period 3.100 -name txclk0_1 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # tcds_tx0
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_0] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_1] -asynchronous
