// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-11-06 10:51:33.145
// User: madorsky
// FPGA MGT builder homepage: <link>

`include "mgt_gth_interfaces.sv"
module assign_mgt_gth_rx
(
	mgt_gth_rx.out dest,
	mgt_gth_rx.in src
);
	 assign dest.gthrxn = src.gthrxn;
	 assign dest.gthrxp = src.gthrxp;
	 assign src.rxctrl0 = dest.rxctrl0;
	 assign src.rxctrl1 = dest.rxctrl1;
	 assign src.rxctrl2 = dest.rxctrl2;
	 assign src.rxctrl3 = dest.rxctrl3;
	 assign src.rxdata = dest.rxdata;
	 assign src.rxdatavalid = dest.rxdatavalid;
	 assign dest.rxgearboxslip = src.rxgearboxslip;
	 assign src.rxheader = dest.rxheader;
	 assign src.rxheadervalid = dest.rxheadervalid;
	 assign dest.rxlatclk = src.rxlatclk;
	 assign src.rxoutclk = dest.rxoutclk;
	 assign dest.rxslide = src.rxslide;
	 assign src.rxstartofseq = dest.rxstartofseq;
endmodule
