// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-11-04 11:46:15.4
// User: madorsky
// FPGA MGT builder homepage: <link>

`include "mgt_interfaces.sv"
module assign_mgt_rx
(
	mgt_rx.out dest,
	mgt_rx.in src
);
	 assign dest.gtyrxp = src.gtyrxp;
	 assign dest.gtyrxn = src.gtyrxn;
	 assign src.rxoutclk = dest.rxoutclk;
	 assign dest.rxslide = src.rxslide;
	 assign src.rxctrl0 = dest.rxctrl0;
	 assign src.rxctrl1 = dest.rxctrl1;
	 assign src.rxctrl2 = dest.rxctrl2;
	 assign src.rxctrl3 = dest.rxctrl3;
	 assign src.rxdatavalid = dest.rxdatavalid;
	 assign dest.rxgearboxslip = src.rxgearboxslip;
	 assign src.rxheader = dest.rxheader;
	 assign src.rxheadervalid = dest.rxheadervalid;
	 assign src.rxstartofseq = dest.rxstartofseq;
	 assign dest.rxlatclk = src.rxlatclk;
	 assign src.rxdata = dest.rxdata;
	 assign dest.rxusrclk = src.rxusrclk;
	 assign dest.rxusrclk2 = src.rxusrclk2;
endmodule
