// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-11-05 15:42:00.585
// User: madorsky
// FPGA MGT builder homepage: <link>

`include "mgt_gth_interfaces.sv"
module assign_mgt_gth_tx
(
	mgt_gth_tx.out dest,
	mgt_gth_tx.in src
);
endmodule
