// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-11-04 11:46:15.4
// User: madorsky
// FPGA MGT builder homepage: <link>

`include "mgt_interfaces.sv"
module assign_mgt_tx
(
	mgt_tx.out dest,
	mgt_tx.in src
);
	 assign dest.txctrl0 = src.txctrl0;
	 assign dest.txctrl1 = src.txctrl1;
	 assign dest.txctrl2 = src.txctrl2;
	 assign dest.txdata = src.txdata;
	 assign dest.txheader = src.txheader;
	 assign dest.txsequence = src.txsequence;
	 assign src.mgtytxp = dest.mgtytxp;
	 assign src.mgtytxn = dest.mgtytxn;
endmodule
