// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-11-04 11:46:15.4
// User: madorsky
// FPGA MGT builder homepage: <link>

`ifndef MGT_INTERFACES_SV
`define MGT_INTERFACES_SV
interface mgt_rx;
	logic        gtyrxp;
	logic        gtyrxn;
	logic        rxoutclk;
	logic        rxslide;
	logic [15:0] rxctrl0;
	logic [15:0] rxctrl1;
	logic [ 7:0] rxctrl2;
	logic [ 7:0] rxctrl3;
	logic [ 1:0] rxdatavalid;
	logic        rxgearboxslip;
	logic [ 5:0] rxheader;
	logic [ 1:0] rxheadervalid;
	logic [ 1:0] rxstartofseq;
	logic        rxlatclk;
	logic [127:0] rxdata;
	logic        rxusrclk;
	logic        rxusrclk2;
	modport in
	(
		input  gtyrxp,
		input  gtyrxn,
		output rxoutclk,
		input  rxslide,
		output rxctrl0,
		output rxctrl1,
		output rxctrl2,
		output rxctrl3,
		output rxdatavalid,
		input  rxgearboxslip,
		output rxheader,
		output rxheadervalid,
		output rxstartofseq,
		input  rxlatclk,
		output rxdata,
		input  rxusrclk,
		input  rxusrclk2
	);
	modport out
	(
		output gtyrxp,
		output gtyrxn,
		input  rxoutclk,
		output rxslide,
		input  rxctrl0,
		input  rxctrl1,
		input  rxctrl2,
		input  rxctrl3,
		input  rxdatavalid,
		output rxgearboxslip,
		input  rxheader,
		input  rxheadervalid,
		input  rxstartofseq,
		output rxlatclk,
		input  rxdata,
		output rxusrclk,
		output rxusrclk2
	);
endinterface

interface mgt_tx;
	logic [15:0] txctrl0;
	logic [15:0] txctrl1;
	logic [ 7:0] txctrl2;
	logic [127:0] txdata;
	logic [ 5:0] txheader;
	logic [ 6:0] txsequence;
	logic        mgtytxp;
	logic        mgtytxn;
	modport in
	(
		input  txctrl0,
		input  txctrl1,
		input  txctrl2,
		input  txdata,
		input  txheader,
		input  txsequence,
		output mgtytxp,
		output mgtytxn
	);
	modport out
	(
		output txctrl0,
		output txctrl1,
		output txctrl2,
		output txdata,
		output txheader,
		output txsequence,
		input  mgtytxp,
		input  mgtytxn
	);
endinterface

`endif
