// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-11-05 15:42:00.585
// User: madorsky
// FPGA MGT builder homepage: <link>

`ifndef MGT_INTERFACES_SV
`define MGT_INTERFACES_SV
interface mgt_gth_rx;
	modport in
	(
	);
	modport out
	(
	);
endinterface

interface mgt_gth_tx;
	modport in
	(
	);
	modport out
	(
	);
endinterface

`endif
