// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-11-04 11:46:15.4
// User: madorsky
// FPGA MGT builder homepage: <link>

`include "drp_interface.sv"
`include "mgt_interfaces.sv"
module GTHE4_QUAD
#(parameter ind = 0)
(
	drp.in drp_qif,
	input drpclk,
	mgt_tx.in mgt_tx_if [3:0],
	mgt_rx.in mgt_rx_if [3:0],
	input  [ 3:0] mgt_qpll0clk,
	input  [ 3:0] mgt_qpll1clk,
	input  [ 3:0] mgt_qpll0refclk,
	input  [ 3:0] mgt_qpll1refclk,
	input         mgt_cplllockdetclk,
	input         mgt_dmonitorclk,
	input  [ 3:0] mgt_txusrclk,
	input  [ 3:0] mgt_txusrclk2,
	input         mgt_txlatclk,
	output [ 1:0] mgt_txbufstatus [ 3:0],
	output [ 3:0] mgt_txoutclk,
	output [ 3:0] mgt_rxphaligndone,
	input         mgt_rxsyncallin,
	input         com_gtrefclk00,
	input         com_gtrefclk01,
	output        com_qpll0outclk,
	output        com_qpll1outclk,
	output        com_qpll0outrefclk,
	output        com_qpll1outrefclk,
	input         com_qpll0lockdetclk,
	input         com_qpll1lockdetclk,
	output        com_qpll0outrefclk,
	output        com_qpll1outrefclk
);
	localparam drpn = 5;
	drp #(.AW(9)) drp_if [drpn-1:0]();
	drp_mux #(.N(drpn), .AW_FPGA(12), .AW_QUAD(9)) drpm (drp_if, drp_qif, drpclk);

	genvar gi;
	generate
		for (gi = 0; gi < 4; gi++)
		begin: mgt_loop
			GTYE4_CHANNEL_tux  #(.qind(ind), .mind(gi)) GTYE4_CHANNEL_tux_inst
			(
				.drp_if (drp_if[gi]),
				.drpclk (drpclk),
				.mgt_tx_if (mgt_tx_if[gi]),
				.mgt_rx_if (mgt_rx_if[gi]),
				.qpll0clk                   (mgt_qpll0clk               [gi]),
				.qpll1clk                   (mgt_qpll1clk               [gi]),
				.qpll0refclk                (mgt_qpll0refclk            [gi]),
				.qpll1refclk                (mgt_qpll1refclk            [gi]),
				.cplllockdetclk             (mgt_cplllockdetclk        ),
				.dmonitorclk                (mgt_dmonitorclk           ),
				.txusrclk                   (mgt_txusrclk               [gi]),
				.txusrclk2                  (mgt_txusrclk2              [gi]),
				.txlatclk                   (mgt_txlatclk              ),
				.txbufstatus                (mgt_txbufstatus            [gi]),
				.txoutclk                   (mgt_txoutclk               [gi]),
				.rxphaligndone              (mgt_rxphaligndone          [gi]),
				.rxsyncallin                (mgt_rxsyncallin           )
			);
		end
		for (gi = 0; gi < 1; gi++)
		begin: common_loop
	GTHE4_COMMON_tux  #(.qind(ind), .mind(gi)) GTHE4_COMMON_tux_inst
	(
		.drp_if (drp_if[gi+4]),
		.drpclk (drpclk),
		.gtrefclk00                 (com_gtrefclk00            ),
		.gtrefclk01                 (com_gtrefclk01            ),
		.qpll0outclk                (com_qpll0outclk           ),
		.qpll1outclk                (com_qpll1outclk           ),
		.qpll0outrefclk             (com_qpll0outrefclk        ),
		.qpll1outrefclk             (com_qpll1outrefclk        ),
		.qpll0lockdetclk            (com_qpll0lockdetclk       ),
		.qpll1lockdetclk            (com_qpll1lockdetclk       ),
		.qpll0outrefclk             (com_qpll0outrefclk        ),
		.qpll1outrefclk             (com_qpll1outrefclk        )
	);
		end
	endgenerate
endmodule
