// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-11-07 15:29:34.756
// User: madorsky
// FPGA MGT builder homepage: <link>

	wire [15:0] mgtxy [0:0][0:1]; // [quad][mgt]
	assign mgtxy[0][0] = 16'ha004;
	assign mgtxy[0][1] = 16'ha005;
