# This code was automatically generated by FPGA MGT Builder
# Timestamp: 2022-10-07 16:04:48.79
# User: madorsky
# FPGA MGT builder homepage: https:#github.com/madorskya/mgt_builder

set_property LOC BD39 [get_ports refclk_p[ 0]]; # name: 120_0 156.25 MHz
set_property LOC BB39 [get_ports refclk_p[ 1]]; # name: 121_0 156.25 MHz
set_property LOC AY39 [get_ports refclk_p[ 2]]; # name: 122_0 156.25 MHz
set_property LOC AV39 [get_ports refclk_p[ 3]]; # name: 123_0 156.25 MHz
set_property LOC AT39 [get_ports refclk_p[ 4]]; # name: 124_0 156.25 MHz
set_property LOC AP39 [get_ports refclk_p[ 5]]; # name: 125_0 156.25 MHz
set_property LOC AM39 [get_ports refclk_p[ 6]]; # name: 126_0 156.25 MHz
set_property LOC AJ41 [get_ports refclk_p[ 7]]; # name: 127_0 156.25 MHz
set_property LOC AE41 [get_ports refclk_p[ 8]]; # name: 128_0 156.25 MHz
set_property LOC AA41 [get_ports refclk_p[ 9]]; # name: 129_0 156.25 MHz
set_property LOC  W41 [get_ports refclk_p[10]]; # name: 130_0 156.25 MHz
set_property LOC  U41 [get_ports refclk_p[11]]; # name: 131_0 156.25 MHz
set_property LOC  R41 [get_ports refclk_p[12]]; # name: 132_0 156.25 MHz
set_property LOC  N41 [get_ports refclk_p[13]]; # name: 133_0 156.25 MHz
set_property LOC  L41 [get_ports refclk_p[14]]; # name: 134_0 156.25 MHz
set_property LOC  J41 [get_ports refclk_p[15]]; # name: 135_0 156.25 MHz
set_property LOC BD13 [get_ports refclk_p[16]]; # name: 220_0 156.25 MHz
set_property LOC BB13 [get_ports refclk_p[17]]; # name: 221_0 156.25 MHz
set_property LOC AY13 [get_ports refclk_p[18]]; # name: 222_0 156.25 MHz
set_property LOC AV13 [get_ports refclk_p[19]]; # name: 223_0 156.25 MHz
set_property LOC AT13 [get_ports refclk_p[20]]; # name: 224_0 156.25 MHz
set_property LOC AP13 [get_ports refclk_p[21]]; # name: 225_0 156.25 MHz
set_property LOC AM13 [get_ports refclk_p[22]]; # name: 226_0 156.25 MHz
set_property LOC AJ11 [get_ports refclk_p[23]]; # name: 227_0 156.25 MHz
set_property LOC AE11 [get_ports refclk_p[24]]; # name: 228_0 156.25 MHz
set_property LOC AA11 [get_ports refclk_p[25]]; # name: 229_0 156.25 MHz
set_property LOC  W11 [get_ports refclk_p[26]]; # name: 230_0 156.25 MHz
set_property LOC  U11 [get_ports refclk_p[27]]; # name: 231_0 156.25 MHz
set_property LOC  R11 [get_ports refclk_p[28]]; # name: 232_0 156.25 MHz
set_property LOC  N11 [get_ports refclk_p[29]]; # name: 233_0 156.25 MHz
set_property LOC  L11 [get_ports refclk_p[30]]; # name: 234_0 156.25 MHz
set_property LOC  J11 [get_ports refclk_p[31]]; # name: 235_0 156.25 MHz
set_property LOC BA41 [get_ports refclk_p[32]]; # name: 121_1 160.32 MHz
set_property LOC AW41 [get_ports refclk_p[33]]; # name: 122_1 160.32 MHz
set_property LOC AN41 [get_ports refclk_p[34]]; # name: 125_1 160.32 MHz
set_property LOC AL41 [get_ports refclk_p[35]]; # name: 126_1 160.32 MHz
set_property LOC  Y39 [get_ports refclk_p[36]]; # name: 129_1 160.32 MHz
set_property LOC  V39 [get_ports refclk_p[37]]; # name: 130_1 160.32 MHz
set_property LOC  P39 [get_ports refclk_p[38]]; # name: 132_1 160.32 MHz
set_property LOC  M39 [get_ports refclk_p[39]]; # name: 133_1 160.32 MHz
set_property LOC BA11 [get_ports refclk_p[40]]; # name: 221_1 160.32 MHz
set_property LOC AW11 [get_ports refclk_p[41]]; # name: 222_1 160.32 MHz
set_property LOC AN11 [get_ports refclk_p[42]]; # name: 225_1 160.32 MHz
set_property LOC AL11 [get_ports refclk_p[43]]; # name: 226_1 160.32 MHz
set_property LOC  Y13 [get_ports refclk_p[44]]; # name: 229_1 160.32 MHz
set_property LOC  V13 [get_ports refclk_p[45]]; # name: 230_1 160.32 MHz
set_property LOC  P13 [get_ports refclk_p[46]]; # name: 232_1 160.32 MHz
set_property LOC  M13 [get_ports refclk_p[47]]; # name: 233_1 160.32 MHz
create_clock -period 6.400 -name refclk_p0  [get_ports refclk_p[ 0]];
create_clock -period 6.400 -name refclk_p1  [get_ports refclk_p[ 1]];
create_clock -period 6.400 -name refclk_p2  [get_ports refclk_p[ 2]];
create_clock -period 6.400 -name refclk_p3  [get_ports refclk_p[ 3]];
create_clock -period 6.400 -name refclk_p4  [get_ports refclk_p[ 4]];
create_clock -period 6.400 -name refclk_p5  [get_ports refclk_p[ 5]];
create_clock -period 6.400 -name refclk_p6  [get_ports refclk_p[ 6]];
create_clock -period 6.400 -name refclk_p7  [get_ports refclk_p[ 7]];
create_clock -period 6.400 -name refclk_p8  [get_ports refclk_p[ 8]];
create_clock -period 6.400 -name refclk_p9  [get_ports refclk_p[ 9]];
create_clock -period 6.400 -name refclk_p10 [get_ports refclk_p[10]];
create_clock -period 6.400 -name refclk_p11 [get_ports refclk_p[11]];
create_clock -period 6.400 -name refclk_p12 [get_ports refclk_p[12]];
create_clock -period 6.400 -name refclk_p13 [get_ports refclk_p[13]];
create_clock -period 6.400 -name refclk_p14 [get_ports refclk_p[14]];
create_clock -period 6.400 -name refclk_p15 [get_ports refclk_p[15]];
create_clock -period 6.400 -name refclk_p16 [get_ports refclk_p[16]];
create_clock -period 6.400 -name refclk_p17 [get_ports refclk_p[17]];
create_clock -period 6.400 -name refclk_p18 [get_ports refclk_p[18]];
create_clock -period 6.400 -name refclk_p19 [get_ports refclk_p[19]];
create_clock -period 6.400 -name refclk_p20 [get_ports refclk_p[20]];
create_clock -period 6.400 -name refclk_p21 [get_ports refclk_p[21]];
create_clock -period 6.400 -name refclk_p22 [get_ports refclk_p[22]];
create_clock -period 6.400 -name refclk_p23 [get_ports refclk_p[23]];
create_clock -period 6.400 -name refclk_p24 [get_ports refclk_p[24]];
create_clock -period 6.400 -name refclk_p25 [get_ports refclk_p[25]];
create_clock -period 6.400 -name refclk_p26 [get_ports refclk_p[26]];
create_clock -period 6.400 -name refclk_p27 [get_ports refclk_p[27]];
create_clock -period 6.400 -name refclk_p28 [get_ports refclk_p[28]];
create_clock -period 6.400 -name refclk_p29 [get_ports refclk_p[29]];
create_clock -period 6.400 -name refclk_p30 [get_ports refclk_p[30]];
create_clock -period 6.400 -name refclk_p31 [get_ports refclk_p[31]];
create_clock -period 6.238 -name refclk_p32 [get_ports refclk_p[32]];
create_clock -period 6.238 -name refclk_p33 [get_ports refclk_p[33]];
create_clock -period 6.238 -name refclk_p34 [get_ports refclk_p[34]];
create_clock -period 6.238 -name refclk_p35 [get_ports refclk_p[35]];
create_clock -period 6.238 -name refclk_p36 [get_ports refclk_p[36]];
create_clock -period 6.238 -name refclk_p37 [get_ports refclk_p[37]];
create_clock -period 6.238 -name refclk_p38 [get_ports refclk_p[38]];
create_clock -period 6.238 -name refclk_p39 [get_ports refclk_p[39]];
create_clock -period 6.238 -name refclk_p40 [get_ports refclk_p[40]];
create_clock -period 6.238 -name refclk_p41 [get_ports refclk_p[41]];
create_clock -period 6.238 -name refclk_p42 [get_ports refclk_p[42]];
create_clock -period 6.238 -name refclk_p43 [get_ports refclk_p[43]];
create_clock -period 6.238 -name refclk_p44 [get_ports refclk_p[44]];
create_clock -period 6.238 -name refclk_p45 [get_ports refclk_p[45]];
create_clock -period 6.238 -name refclk_p46 [get_ports refclk_p[46]];
create_clock -period 6.238 -name refclk_p47 [get_ports refclk_p[47]];
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p0 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p1 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p2 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p3 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p4 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p5 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p6 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p7 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p8 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p9 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p11] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p12] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p13] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p14] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p15] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p16] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p17] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p18] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p19] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p20] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p21] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p22] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p23] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p24] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p25] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p26] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p27] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p28] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p29] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p30] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p31] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p32] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p33] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p34] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p35] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p36] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p37] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p38] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p39] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p40] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p41] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p42] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p43] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p44] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p45] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p46] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p47] -asynchronous
set_property LOC GTYE4_CHANNEL_X0Y8  [get_cells */quad_loop[ 0].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y9  [get_cells */quad_loop[ 0].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y10 [get_cells */quad_loop[ 0].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y11 [get_cells */quad_loop[ 0].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y12 [get_cells */quad_loop[ 1].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y13 [get_cells */quad_loop[ 1].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y14 [get_cells */quad_loop[ 1].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y15 [get_cells */quad_loop[ 1].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y16 [get_cells */quad_loop[ 2].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y17 [get_cells */quad_loop[ 2].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y18 [get_cells */quad_loop[ 2].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y19 [get_cells */quad_loop[ 2].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y20 [get_cells */quad_loop[ 3].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y21 [get_cells */quad_loop[ 3].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y22 [get_cells */quad_loop[ 3].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y23 [get_cells */quad_loop[ 3].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y24 [get_cells */quad_loop[ 4].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y25 [get_cells */quad_loop[ 4].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X0Y26 [get_cells */quad_loop[ 4].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y0  [get_cells */quad_loop[ 5].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y1  [get_cells */quad_loop[ 5].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y2  [get_cells */quad_loop[ 5].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y3  [get_cells */quad_loop[ 5].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y4  [get_cells */quad_loop[ 6].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y5  [get_cells */quad_loop[ 6].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y6  [get_cells */quad_loop[ 6].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y7  [get_cells */quad_loop[ 6].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y8  [get_cells */quad_loop[ 7].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y9  [get_cells */quad_loop[ 7].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y10 [get_cells */quad_loop[ 7].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y11 [get_cells */quad_loop[ 7].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y12 [get_cells */quad_loop[ 8].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y13 [get_cells */quad_loop[ 8].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y14 [get_cells */quad_loop[ 8].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y15 [get_cells */quad_loop[ 8].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y16 [get_cells */quad_loop[ 9].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y17 [get_cells */quad_loop[ 9].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y18 [get_cells */quad_loop[ 9].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y19 [get_cells */quad_loop[ 9].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y20 [get_cells */quad_loop[10].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y21 [get_cells */quad_loop[10].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y22 [get_cells */quad_loop[10].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y23 [get_cells */quad_loop[10].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y24 [get_cells */quad_loop[11].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y25 [get_cells */quad_loop[11].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y26 [get_cells */quad_loop[11].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y27 [get_cells */quad_loop[11].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y28 [get_cells */quad_loop[12].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y29 [get_cells */quad_loop[12].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y30 [get_cells */quad_loop[12].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y31 [get_cells */quad_loop[12].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y32 [get_cells */quad_loop[13].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y33 [get_cells */quad_loop[13].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y34 [get_cells */quad_loop[13].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y35 [get_cells */quad_loop[13].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y36 [get_cells */quad_loop[14].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y37 [get_cells */quad_loop[14].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y38 [get_cells */quad_loop[14].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y39 [get_cells */quad_loop[14].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y40 [get_cells */quad_loop[15].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y41 [get_cells */quad_loop[15].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y42 [get_cells */quad_loop[15].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y43 [get_cells */quad_loop[15].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y44 [get_cells */quad_loop[16].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y45 [get_cells */quad_loop[16].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y46 [get_cells */quad_loop[16].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y47 [get_cells */quad_loop[16].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y48 [get_cells */quad_loop[17].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y49 [get_cells */quad_loop[17].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y50 [get_cells */quad_loop[17].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y51 [get_cells */quad_loop[17].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y52 [get_cells */quad_loop[18].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y53 [get_cells */quad_loop[18].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y54 [get_cells */quad_loop[18].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y55 [get_cells */quad_loop[18].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y56 [get_cells */quad_loop[19].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y57 [get_cells */quad_loop[19].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y58 [get_cells */quad_loop[19].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y59 [get_cells */quad_loop[19].GTYE4_QUAD_inst/mgt_loop[ 3].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y60 [get_cells */quad_loop[20].GTYE4_QUAD_inst/mgt_loop[ 0].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y61 [get_cells */quad_loop[20].GTYE4_QUAD_inst/mgt_loop[ 1].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
set_property LOC GTYE4_CHANNEL_X1Y62 [get_cells */quad_loop[20].GTYE4_QUAD_inst/mgt_loop[ 2].GTYE4_CHANNEL_tux_inst/GTYE4_CHANNEL_inst];
create_clock -period 2.550 -name txclk0_8 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # daq_tx0
create_clock -period 2.550 -name txclk0_9 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # gmt_tx0
create_clock -period 2.550 -name txclk0_10 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # gmt_tx1
create_clock -period 2.550 -name txclk0_11 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # gmt_tx2
create_clock -period 2.550 -name txclk0_12 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # gmt_tx3
create_clock -period 2.550 -name txclk0_13 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # gmt_tx4
create_clock -period 2.550 -name txclk0_14 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # gmt_tx5
create_clock -period 2.550 -name txclk0_15 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # gmt_tx6
create_clock -period 2.550 -name txclk0_16 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # gmt_tx7
create_clock -period 2.550 -name txclk0_17 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # gmt_tx8
create_clock -period 2.550 -name txclk0_18 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # gmt_tx9
create_clock -period 2.550 -name txclk0_19 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # gmt_tx10
create_clock -period 2.550 -name txclk0_20 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # gmt_tx11
create_clock -period 2.550 -name txclk0_21 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # gmt_tx12
create_clock -period 2.550 -name txclk0_22 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # gmt_tx13
create_clock -period 2.550 -name txclk0_23 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # gmt_tx14
create_clock -period 2.550 -name txclk0_24 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # gmt_tx15
create_clock -period 2.550 -name txclk0_25 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # gmt_tx16
create_clock -period 2.550 -name txclk0_26 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # gmt_tx17
create_clock -period 12.470 -name rxclk1_0 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpc0_rx0
create_clock -period 12.470 -name rxclk1_1 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpc0_rx1
create_clock -period 12.470 -name rxclk1_2 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpc0_rx2
create_clock -period 12.470 -name rxclk1_3 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpc0_rx3
create_clock -period 12.470 -name rxclk1_4 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpc0_rx4
create_clock -period 12.470 -name rxclk1_5 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpc0_rx5
create_clock -period 12.470 -name rxclk1_6 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpc0_rx6
create_clock -period 12.470 -name rxclk1_7 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpc0_rx7
create_clock -period 12.470 -name rxclk1_8 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpc1_rx0
create_clock -period 12.470 -name rxclk1_9 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpc1_rx1
create_clock -period 12.470 -name rxclk1_10 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpc1_rx2
create_clock -period 12.470 -name rxclk1_11 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpc1_rx3
create_clock -period 12.470 -name rxclk1_12 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpc1_rx4
create_clock -period 12.470 -name rxclk1_13 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpc1_rx5
create_clock -period 12.470 -name rxclk1_14 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpc1_rx6
create_clock -period 12.470 -name rxclk1_15 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpc1_rx7
create_clock -period 12.470 -name rxclk1_16 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpc2_rx0
create_clock -period 12.470 -name rxclk1_17 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpc2_rx1
create_clock -period 12.470 -name rxclk1_18 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpc2_rx2
create_clock -period 12.470 -name rxclk1_19 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[9]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpc2_rx3
create_clock -period 12.470 -name rxclk1_20 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpc2_rx4
create_clock -period 12.470 -name rxclk1_21 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpc2_rx5
create_clock -period 12.470 -name rxclk1_22 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpc2_rx6
create_clock -period 12.470 -name rxclk1_23 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[10]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpc2_rx7
create_clock -period 12.470 -name rxclk1_24 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpc3_rx0
create_clock -period 12.470 -name rxclk1_25 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpc3_rx1
create_clock -period 12.470 -name rxclk1_26 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpc3_rx2
create_clock -period 12.470 -name rxclk1_27 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[11]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpc3_rx3
create_clock -period 12.470 -name rxclk1_28 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpc3_rx4
create_clock -period 12.470 -name rxclk1_29 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpc3_rx5
create_clock -period 12.470 -name rxclk1_30 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpc3_rx6
create_clock -period 12.470 -name rxclk1_31 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[12]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpc3_rx7
create_clock -period 12.470 -name rxclk1_32 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpc4_rx0
create_clock -period 12.470 -name rxclk1_33 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpc4_rx1
create_clock -period 12.470 -name rxclk1_34 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpc4_rx2
create_clock -period 12.470 -name rxclk1_35 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[13]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpc4_rx3
create_clock -period 12.470 -name rxclk1_36 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpc4_rx4
create_clock -period 12.470 -name rxclk1_37 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpc4_rx5
create_clock -period 12.470 -name rxclk1_38 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpc4_rx6
create_clock -period 12.470 -name rxclk1_39 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[14]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpc4_rx7
create_clock -period 4.000 -name rxclk1_40 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # cppf_rx6
create_clock -period 4.000 -name rxclk1_41 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # cppf_rx5
create_clock -period 4.000 -name rxclk1_42 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # cppf_rx0
create_clock -period 4.000 -name rxclk1_43 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[15]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # cppf_rx1
create_clock -period 4.000 -name rxclk1_44 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # cppf_rx3
create_clock -period 4.000 -name rxclk1_45 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # cppf_rx4
create_clock -period 4.000 -name rxclk1_46 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # cppf_rx2
create_clock -period 12.470 -name rxclk1_47 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[16]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpcn_rx0
create_clock -period 12.470 -name rxclk1_48 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpcn_rx1
create_clock -period 12.470 -name rxclk1_49 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpcn_rx2
create_clock -period 12.470 -name rxclk1_50 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpcn_rx3
create_clock -period 12.470 -name rxclk1_51 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[17]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpcn_rx4
create_clock -period 12.470 -name rxclk1_52 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # mpcn_rx5
create_clock -period 12.470 -name rxclk1_53 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # mpcn_rx6
create_clock -period 12.470 -name rxclk1_54 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # mpcn_rx7
create_clock -period 12.470 -name rxclk1_55 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[18]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # mpcn_rx8
create_clock -period 3.890 -name rxclk1_56 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # ge11_rx0
create_clock -period 3.890 -name rxclk1_57 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # ge11_rx1
create_clock -period 3.890 -name rxclk1_58 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # ge11_rx2
create_clock -period 3.890 -name rxclk1_59 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[19]*mgt_loop[3]*GTYE4_CHANNEL_inst*}]]; # ge11_rx3
create_clock -period 3.890 -name rxclk1_60 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[0]*GTYE4_CHANNEL_inst*}]]; # ge11_rx4
create_clock -period 3.890 -name rxclk1_61 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[1]*GTYE4_CHANNEL_inst*}]]; # ge11_rx5
create_clock -period 3.890 -name rxclk1_62 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[20]*mgt_loop[2]*GTYE4_CHANNEL_inst*}]]; # ge11_rx6
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_8] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_9] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_11] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_12] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_13] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_14] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_15] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_16] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_17] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_18] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_19] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_20] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_21] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_22] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_23] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_24] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_25] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_26] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_0] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_1] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_2] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_3] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_4] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_5] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_6] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_7] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_8] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_9] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_11] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_12] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_13] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_14] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_15] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_16] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_17] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_18] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_19] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_20] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_21] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_22] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_23] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_24] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_25] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_26] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_27] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_28] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_29] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_30] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_31] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_32] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_33] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_34] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_35] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_36] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_37] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_38] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_39] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_40] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_41] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_42] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_43] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_44] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_45] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_46] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_47] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_48] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_49] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_50] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_51] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_52] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_53] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_54] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_55] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_56] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_57] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_58] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_59] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_60] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_61] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_62] -asynchronous
