// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-11-06 17:35:01.57
// User: madorsky
// FPGA MGT builder homepage: <link>

	wire [15:0] mgtxy [0:0][0:1]; // [quad][mgt]
	assign mgtxy[0][0] = 16'ha000;
	assign mgtxy[0][1] = 16'ha001;
