# This code was automatically generated by FPGA MGT Builder
# Timestamp: 2021-06-09 13:05:44.027
# User: madorsky
# FPGA MGT builder homepage: <link>

set_property LOC AR10 [get_ports refclk_p[ 0]]; # name: 111_0 125.0 MHz
set_property LOC  AF8 [get_ports refclk_p[ 1]]; # name: 113_0 125.0 MHz
set_property LOC  N10 [get_ports refclk_p[ 2]]; # name: 116_0 125.0 MHz
set_property LOC  E10 [get_ports refclk_p[ 3]]; # name: 118_0 125.0 MHz
set_property LOC AR35 [get_ports refclk_p[ 4]]; # name: 211_0 125.0 MHz
set_property LOC AF37 [get_ports refclk_p[ 5]]; # name: 213_0 125.0 MHz
set_property LOC  N35 [get_ports refclk_p[ 6]]; # name: 216_0 125.0 MHz
set_property LOC  E35 [get_ports refclk_p[ 7]]; # name: 218_0 125.0 MHz
set_property LOC  BB8 [get_ports refclk_p[ 8]]; # name: 110_1 640.0 MHz
set_property LOC  AH8 [get_ports refclk_p[ 9]]; # name: 113_1 640.0 MHz
set_property LOC  R10 [get_ports refclk_p[10]]; # name: 116_1 640.0 MHz
set_property LOC  G10 [get_ports refclk_p[11]]; # name: 118_1 640.0 MHz
set_property LOC AT37 [get_ports refclk_p[12]]; # name: 211_1 640.0 MHz
set_property LOC AH37 [get_ports refclk_p[13]]; # name: 213_1 640.0 MHz
set_property LOC  R35 [get_ports refclk_p[14]]; # name: 216_1 640.0 MHz
set_property LOC  G35 [get_ports refclk_p[15]]; # name: 218_1 640.0 MHz
create_clock -period 8.000 -name refclk_p0  [get_ports refclk_p[ 0]];
create_clock -period 8.000 -name refclk_p1  [get_ports refclk_p[ 1]];
create_clock -period 8.000 -name refclk_p2  [get_ports refclk_p[ 2]];
create_clock -period 8.000 -name refclk_p3  [get_ports refclk_p[ 3]];
create_clock -period 8.000 -name refclk_p4  [get_ports refclk_p[ 4]];
create_clock -period 8.000 -name refclk_p5  [get_ports refclk_p[ 5]];
create_clock -period 8.000 -name refclk_p6  [get_ports refclk_p[ 6]];
create_clock -period 8.000 -name refclk_p7  [get_ports refclk_p[ 7]];
create_clock -period 1.563 -name refclk_p8  [get_ports refclk_p[ 8]];
create_clock -period 1.563 -name refclk_p9  [get_ports refclk_p[ 9]];
create_clock -period 1.563 -name refclk_p10 [get_ports refclk_p[10]];
create_clock -period 1.563 -name refclk_p11 [get_ports refclk_p[11]];
create_clock -period 1.563 -name refclk_p12 [get_ports refclk_p[12]];
create_clock -period 1.563 -name refclk_p13 [get_ports refclk_p[13]];
create_clock -period 1.563 -name refclk_p14 [get_ports refclk_p[14]];
create_clock -period 1.563 -name refclk_p15 [get_ports refclk_p[15]];
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p0 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p1 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p2 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p3 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p4 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p5 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p6 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p7 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p8 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p9 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p11] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p12] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p13] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p14] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p15] -asynchronous
set_property LOC GTHE2_CHANNEL_X0Y4  [get_cells */quad_loop[ 0].GTHE2_QUAD_inst/mgt_loop[ 0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y5  [get_cells */quad_loop[ 0].GTHE2_QUAD_inst/mgt_loop[ 1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y6  [get_cells */quad_loop[ 0].GTHE2_QUAD_inst/mgt_loop[ 2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y7  [get_cells */quad_loop[ 0].GTHE2_QUAD_inst/mgt_loop[ 3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
create_clock -period 6.250 -name rxclk0_4 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # mpc0_rx0
create_clock -period 6.250 -name rxclk0_5 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # mpc0_rx1
create_clock -period 6.250 -name rxclk0_6 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]; # mpc0_rx2
create_clock -period 6.250 -name rxclk0_7 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]; # mpc0_rx3
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_4] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_5] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_6] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_7] -asynchronous
