// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2021-06-09 13:05:44.027
// User: madorsky
// FPGA MGT builder homepage: <link>

	wire [15:0] mgtxy [0:0][0:3]; // [quad][mgt]
	assign mgtxy[0][0] = 16'ha004;
	assign mgtxy[0][1] = 16'ha005;
	assign mgtxy[0][2] = 16'ha006;
	assign mgtxy[0][3] = 16'ha007;
