# This code was automatically generated by FPGA MGT Builder
# Timestamp: 2020-05-04 19:53:48.872
# User: madorsky
# FPGA MGT builder homepage: <link>

set_property LOC AR10 [get_ports refclk_p[ 0]]; # name: 111_0 125.0 MHz
set_property LOC  AF8 [get_ports refclk_p[ 1]]; # name: 113_0 125.0 MHz
set_property LOC  N10 [get_ports refclk_p[ 2]]; # name: 116_0 125.0 MHz
set_property LOC  E10 [get_ports refclk_p[ 3]]; # name: 118_0 125.0 MHz
set_property LOC AR35 [get_ports refclk_p[ 4]]; # name: 211_0 125.0 MHz
set_property LOC AF37 [get_ports refclk_p[ 5]]; # name: 213_0 125.0 MHz
set_property LOC  N35 [get_ports refclk_p[ 6]]; # name: 216_0 125.0 MHz
set_property LOC  E35 [get_ports refclk_p[ 7]]; # name: 218_0 125.0 MHz
set_property LOC  BB8 [get_ports refclk_p[ 8]]; # name: 110_1 640.0 MHz
set_property LOC  AH8 [get_ports refclk_p[ 9]]; # name: 113_1 640.0 MHz
set_property LOC  R10 [get_ports refclk_p[10]]; # name: 116_1 640.0 MHz
set_property LOC  G10 [get_ports refclk_p[11]]; # name: 118_1 640.0 MHz
set_property LOC AT37 [get_ports refclk_p[12]]; # name: 211_1 640.0 MHz
set_property LOC AH37 [get_ports refclk_p[13]]; # name: 213_1 640.0 MHz
set_property LOC  R35 [get_ports refclk_p[14]]; # name: 216_1 640.0 MHz
set_property LOC  G35 [get_ports refclk_p[15]]; # name: 218_1 640.0 MHz
create_clock -period 8.000 -name refclk_p0  [get_ports refclk_p[ 0]];
create_clock -period 8.000 -name refclk_p1  [get_ports refclk_p[ 1]];
create_clock -period 8.000 -name refclk_p2  [get_ports refclk_p[ 2]];
create_clock -period 8.000 -name refclk_p3  [get_ports refclk_p[ 3]];
create_clock -period 8.000 -name refclk_p4  [get_ports refclk_p[ 4]];
create_clock -period 8.000 -name refclk_p5  [get_ports refclk_p[ 5]];
create_clock -period 8.000 -name refclk_p6  [get_ports refclk_p[ 6]];
create_clock -period 8.000 -name refclk_p7  [get_ports refclk_p[ 7]];
create_clock -period 1.563 -name refclk_p8  [get_ports refclk_p[ 8]];
create_clock -period 1.563 -name refclk_p9  [get_ports refclk_p[ 9]];
create_clock -period 1.563 -name refclk_p10 [get_ports refclk_p[10]];
create_clock -period 1.563 -name refclk_p11 [get_ports refclk_p[11]];
create_clock -period 1.563 -name refclk_p12 [get_ports refclk_p[12]];
create_clock -period 1.563 -name refclk_p13 [get_ports refclk_p[13]];
create_clock -period 1.563 -name refclk_p14 [get_ports refclk_p[14]];
create_clock -period 1.563 -name refclk_p15 [get_ports refclk_p[15]];
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p0 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p1 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p2 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p3 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p4 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p5 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p6 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p7 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p8 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p9 ] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p11] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p12] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p13] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p14] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks refclk_p15] -asynchronous
set_property LOC GTHE2_CHANNEL_X0Y4  [get_cells */quad_loop[ 0].GTHE2_QUAD_inst/mgt_loop[ 0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y5  [get_cells */quad_loop[ 0].GTHE2_QUAD_inst/mgt_loop[ 1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y6  [get_cells */quad_loop[ 0].GTHE2_QUAD_inst/mgt_loop[ 2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y7  [get_cells */quad_loop[ 0].GTHE2_QUAD_inst/mgt_loop[ 3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y8  [get_cells */quad_loop[ 1].GTHE2_QUAD_inst/mgt_loop[ 0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y10 [get_cells */quad_loop[ 1].GTHE2_QUAD_inst/mgt_loop[ 2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y28 [get_cells */quad_loop[ 2].GTHE2_QUAD_inst/mgt_loop[ 0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y29 [get_cells */quad_loop[ 2].GTHE2_QUAD_inst/mgt_loop[ 1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y30 [get_cells */quad_loop[ 2].GTHE2_QUAD_inst/mgt_loop[ 2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y31 [get_cells */quad_loop[ 2].GTHE2_QUAD_inst/mgt_loop[ 3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y32 [get_cells */quad_loop[ 3].GTHE2_QUAD_inst/mgt_loop[ 0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y33 [get_cells */quad_loop[ 3].GTHE2_QUAD_inst/mgt_loop[ 1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y34 [get_cells */quad_loop[ 3].GTHE2_QUAD_inst/mgt_loop[ 2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y35 [get_cells */quad_loop[ 3].GTHE2_QUAD_inst/mgt_loop[ 3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y36 [get_cells */quad_loop[ 4].GTHE2_QUAD_inst/mgt_loop[ 0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y37 [get_cells */quad_loop[ 4].GTHE2_QUAD_inst/mgt_loop[ 1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y38 [get_cells */quad_loop[ 4].GTHE2_QUAD_inst/mgt_loop[ 2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X0Y39 [get_cells */quad_loop[ 4].GTHE2_QUAD_inst/mgt_loop[ 3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y4  [get_cells */quad_loop[ 5].GTHE2_QUAD_inst/mgt_loop[ 0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y5  [get_cells */quad_loop[ 5].GTHE2_QUAD_inst/mgt_loop[ 1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y6  [get_cells */quad_loop[ 5].GTHE2_QUAD_inst/mgt_loop[ 2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y7  [get_cells */quad_loop[ 5].GTHE2_QUAD_inst/mgt_loop[ 3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y8  [get_cells */quad_loop[ 6].GTHE2_QUAD_inst/mgt_loop[ 0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y9  [get_cells */quad_loop[ 6].GTHE2_QUAD_inst/mgt_loop[ 1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y34 [get_cells */quad_loop[ 7].GTHE2_QUAD_inst/mgt_loop[ 2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y35 [get_cells */quad_loop[ 7].GTHE2_QUAD_inst/mgt_loop[ 3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y36 [get_cells */quad_loop[ 8].GTHE2_QUAD_inst/mgt_loop[ 0].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y37 [get_cells */quad_loop[ 8].GTHE2_QUAD_inst/mgt_loop[ 1].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y38 [get_cells */quad_loop[ 8].GTHE2_QUAD_inst/mgt_loop[ 2].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
set_property LOC GTHE2_CHANNEL_X1Y39 [get_cells */quad_loop[ 8].GTHE2_QUAD_inst/mgt_loop[ 3].GTHE2_CHANNEL_tux_inst/GTHE2_CHANNEL_inst];
create_clock -period 6.250 -name rxclk0_4 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx23
create_clock -period 6.250 -name rxclk0_5 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx22
create_clock -period 6.250 -name rxclk0_6 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx18
create_clock -period 6.250 -name rxclk0_7 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[0]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx19
create_clock -period 6.250 -name rxclk0_8 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx14
create_clock -period 6.250 -name rxclk0_10 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[1]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx15
create_clock -period 6.250 -name txclk0_28 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx3
create_clock -period 6.250 -name txclk0_29 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx2
create_clock -period 6.250 -name txclk0_30 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx1
create_clock -period 6.250 -name txclk0_31 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[2]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx0
create_clock -period 6.250 -name txclk0_32 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx5
create_clock -period 6.250 -name rxclk0_33 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx11
create_clock -period 6.250 -name txclk0_33 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx4
create_clock -period 6.250 -name txclk0_34 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx9
create_clock -period 6.250 -name rxclk0_35 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx7
create_clock -period 6.250 -name txclk0_35 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[3]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx8
create_clock -period 6.250 -name rxclk0_36 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx10
create_clock -period 6.250 -name txclk0_36 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx7
create_clock -period 6.250 -name rxclk0_37 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx6
create_clock -period 6.250 -name txclk0_37 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx6
create_clock -period 6.250 -name rxclk0_38 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx3
create_clock -period 6.250 -name txclk0_38 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx10
create_clock -period 6.250 -name rxclk0_39 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx2
create_clock -period 6.250 -name txclk0_39 [get_pins -filter {REF_PIN_NAME=~*TXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[4]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]; # mpcx_tx11
create_clock -period 6.250 -name rxclk1_4 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx20
create_clock -period 6.250 -name rxclk1_5 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx21
create_clock -period 6.250 -name rxclk1_6 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx17
create_clock -period 6.250 -name rxclk1_7 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[5]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx16
create_clock -period 6.250 -name rxclk1_8 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx13
create_clock -period 6.250 -name rxclk1_9 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[6]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx12
create_clock -period 6.250 -name rxclk1_34 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx9
create_clock -period 6.250 -name rxclk1_35 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[7]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx8
create_clock -period 6.250 -name rxclk1_36 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[0]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx5
create_clock -period 6.250 -name rxclk1_37 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[1]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx1
create_clock -period 6.250 -name rxclk1_38 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[2]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx4
create_clock -period 6.250 -name rxclk1_39 [get_pins -filter {REF_PIN_NAME=~*RXOUTCLK} -of_objects [get_cells -hierarchical -filter {NAME =~ *quad_loop[8]*mgt_loop[3]*GTHE2_CHANNEL_inst*}]]; # mpcx_rx0
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_4] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_5] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_6] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_7] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_8] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_10] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_28] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_29] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_30] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_31] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_32] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_33] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_33] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_34] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_35] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_35] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_36] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_36] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_37] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_37] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_38] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_38] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk0_39] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks txclk0_39] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_4] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_5] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_6] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_7] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_8] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_9] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_34] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_35] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_36] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_37] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_38] -asynchronous
set_clock_groups -group [get_clocks -include_generated_clocks rxclk1_39] -asynchronous
