// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2020-05-04 19:53:48.872
// User: madorsky
// FPGA MGT builder homepage: <link>

	wire [15:0] mgtxy [0:8][0:3]; // [quad][mgt]
	assign mgtxy[0][0] = 16'ha004;
	assign mgtxy[0][1] = 16'ha005;
	assign mgtxy[0][2] = 16'ha006;
	assign mgtxy[0][3] = 16'ha007;
	assign mgtxy[1][0] = 16'ha008;
	assign mgtxy[1][2] = 16'ha010;
	assign mgtxy[2][0] = 16'ha028;
	assign mgtxy[2][1] = 16'ha029;
	assign mgtxy[2][2] = 16'ha030;
	assign mgtxy[2][3] = 16'ha031;
	assign mgtxy[3][0] = 16'ha032;
	assign mgtxy[3][1] = 16'ha033;
	assign mgtxy[3][2] = 16'ha034;
	assign mgtxy[3][3] = 16'ha035;
	assign mgtxy[4][0] = 16'ha036;
	assign mgtxy[4][1] = 16'ha037;
	assign mgtxy[4][2] = 16'ha038;
	assign mgtxy[4][3] = 16'ha039;
	assign mgtxy[5][0] = 16'ha104;
	assign mgtxy[5][1] = 16'ha105;
	assign mgtxy[5][2] = 16'ha106;
	assign mgtxy[5][3] = 16'ha107;
	assign mgtxy[6][0] = 16'ha108;
	assign mgtxy[6][1] = 16'ha109;
	assign mgtxy[7][2] = 16'ha134;
	assign mgtxy[7][3] = 16'ha135;
	assign mgtxy[8][0] = 16'ha136;
	assign mgtxy[8][1] = 16'ha137;
	assign mgtxy[8][2] = 16'ha138;
	assign mgtxy[8][3] = 16'ha139;
