// This code was automatically generated by FPGA MGT Builder
// Timestamp: 2021-04-23 18:24:59.887
// User: madorsky
// FPGA MGT builder homepage: <link>

`include "drp_interface.sv"
`include "mgt_gty_interfaces.sv"
module apex_ku15p_gty_serial_io
(
	drp.in drp_gty_fif,
	input drpclk,
	input [5:0] refclk_p,
	input [5:0] refclk_n,
	mgt_gty_rx.in p25g [0:0],
	mgt_gty_tx.in p25g [0:0],
	output 25g_5_mmcm_clk
);
	localparam quadn = 1;
	drp #(.AW(13)) drp_gty_qif [quadn-1:0]();
	drp_mux_fpga #(.N(quadn), .AW_QUAD(13)) drpm (drp_gty_qif, drp_gty_fif, drpclk);

	mgt_gty_tx mgt_gty_tx_if [quadn-1:0][3:0]();
	mgt_gty_rx mgt_gty_rx_if [quadn-1:0][3:0]();
	wire        mgt_txlatclk ;
	wire [ 3:0] mgt_txusrclk [quadn-1:0];
	wire        com_gtrefclk00 [quadn-1:0];
	wire        com_gtrefclk01 [quadn-1:0];
	wire [5:0] refclk;
	genvar gi;
	generate
		for (gi = 0; gi < quadn; gi++)
		begin: quad_loop
			GTYE4_QUAD #(.ind(gi)) GTYE4_QUAD_inst
			(
				.drp_gty_qif (drp_gty_qif [gi]),
				.drpclk (drpclk),
				.mgt_gty_tx_if (mgt_gty_tx_if [gi]),
				.mgt_gty_rx_if (mgt_gty_rx_if [gi]),
				.mgt_txlatclk               (mgt_txlatclk              ),
				.mgt_txusrclk               (mgt_txusrclk               [gi]),
				.com_gtrefclk00             (com_gtrefclk00             [gi]),
				.com_gtrefclk01             (com_gtrefclk01             [gi])
			);
		end
		for (gi = 0; gi < 6; gi++)
		begin: refclk_loop
			IBUFDS_GTE4 #
			(
				.REFCLK_EN_TX_PATH  (1'b0),
				.REFCLK_HROW_CK_SEL (2'b00),
				.REFCLK_ICNTL_RX    (2'b00)
			) 
			refclk_buf
			(
				.I     (refclk_p [gi]),
				.IB    (refclk_n [gi]),
				.CEB   (1'b0),
				.O     (refclk   [gi]),
				.ODIV2 ()
			);
		end
	endgenerate
	assign_mgt_gty_rx ari0 (mgt_gty_rx_if [0][0], p25g [0]);
	assign_mgt_gty_tx ati0 (mgt_gty_tx_if [0][0], p25g [0]);
	assign com_gtrefclk00 [0] = refclk [5]; // p25g 0
	25g_mmcm 25g_5_inst (.O(25g_5_mmcm_clk), .I(mgt_gty_tx_if[0][0].txoutclk));
	assign mgt_txusrclk[0][0] = 25g_5_mmcm_clk; // p25g0
endmodule
